package infer

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"sync/atomic"
	"testing"

	ort "github.com/yalue/onnxruntime_go"
)

// toy.onnx (testdata, generated by scripts in the ML roadmap work) computes
// y = relu(x + 1) on a 1×3×2×2 float input — real kernels, trivial weights.
const toyLen = 1 * 3 * 2 * 2

func toySpec(t *testing.T, dir string) ModelSpec {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "toy.onnx"))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "toy-1.onnx"), data, 0o644); err != nil {
		t.Fatal(err)
	}
	return ModelSpec{ID: "toy", Version: "1"}
}

func requireRuntime(t *testing.T) {
	t.Helper()
	if err := EnsureRuntime(); err != nil {
		t.Skipf("ONNX Runtime unavailable (run `npm run setup:ort`): %v", err)
	}
}

func TestToyModelRun(t *testing.T) {
	requireRuntime(t)
	dir := t.TempDir()
	m := NewManager(dir)
	s, err := m.Session(context.Background(), toySpec(t, dir), nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(s.Inputs) != 1 || s.Inputs[0].Name != "x" || len(s.Outputs) != 1 || s.Outputs[0].Name != "y" {
		t.Fatalf("unexpected I/O signature: in=%v out=%v", s.Inputs, s.Outputs)
	}

	in := make([]float32, toyLen)
	for i := range in {
		in[i] = float32(i) - 6 // -6..5 → relu(x+1) clips the low half
	}
	tensor, err := ort.NewTensor(ort.NewShape(1, 3, 2, 2), in)
	if err != nil {
		t.Fatal(err)
	}
	defer tensor.Destroy()

	outs, err := s.Run(context.Background(), tensor)
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		for _, o := range outs {
			o.Destroy()
		}
	}()
	got := outs[0].(*ort.Tensor[float32]).GetData()
	if len(got) != toyLen {
		t.Fatalf("output length %d, want %d", len(got), toyLen)
	}
	for i, x := range in {
		want := x + 1
		if want < 0 {
			want = 0
		}
		if got[i] != want {
			t.Errorf("y[%d] = %v, want relu(%v+1) = %v", i, got[i], x, want)
		}
	}

	// Second request must hit the session cache.
	s2, err := m.Session(context.Background(), ModelSpec{ID: "toy", Version: "1"}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if s2 != s {
		t.Error("expected cached session on second request")
	}
}

func TestRunCancelledContext(t *testing.T) {
	requireRuntime(t)
	dir := t.TempDir()
	m := NewManager(dir)
	s, err := m.Session(context.Background(), toySpec(t, dir), nil)
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := s.Run(ctx); !errors.Is(err, context.Canceled) {
		t.Fatalf("Run on cancelled ctx = %v, want context.Canceled", err)
	}
}

func TestEnsureModelDownload(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("testdata", "toy.onnx"))
	if err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(data)

	var hits atomic.Int32
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		hits.Add(1)
		w.Write(data)
	}))
	defer srv.Close()

	m := NewManager(filepath.Join(t.TempDir(), "models")) // dir must be created on demand
	spec := ModelSpec{
		ID: "toy", Version: "1",
		URL:    srv.URL,
		SHA256: hex.EncodeToString(sum[:]),
	}

	var finalDone, finalTotal int64
	path, err := m.ensureModel(context.Background(), spec, func(done, total int64) {
		finalDone, finalTotal = done, total
	})
	if err != nil {
		t.Fatal(err)
	}
	if got, _ := os.ReadFile(path); string(got) != string(data) {
		t.Fatal("downloaded file does not match source")
	}
	if finalDone != int64(len(data)) || finalTotal != int64(len(data)) {
		t.Errorf("final progress %d/%d, want %d/%d", finalDone, finalTotal, len(data), len(data))
	}

	// Second call: file exists, no HTTP.
	if _, err := m.ensureModel(context.Background(), spec, nil); err != nil {
		t.Fatal(err)
	}
	if n := hits.Load(); n != 1 {
		t.Errorf("server hit %d times, want 1", n)
	}

	// No stray .part files.
	parts, _ := filepath.Glob(filepath.Join(m.modelsDir, "*.part-*"))
	if len(parts) != 0 {
		t.Errorf("leftover temp files: %v", parts)
	}
}

func TestEnsureModelBadHash(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("not the model"))
	}))
	defer srv.Close()

	m := NewManager(t.TempDir())
	spec := ModelSpec{ID: "toy", Version: "1", URL: srv.URL, SHA256: "00ff"}
	if _, err := m.ensureModel(context.Background(), spec, nil); err == nil {
		t.Fatal("expected hash mismatch error")
	}
	files, _ := filepath.Glob(filepath.Join(m.modelsDir, "*.onnx"))
	if len(files) != 0 {
		t.Errorf("bad download left model files behind: %v", files)
	}
}

func TestEnsureModelCancel(t *testing.T) {
	release := make(chan struct{})
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Length", "1000000")
		w.Write(make([]byte, 1024))
		w.(http.Flusher).Flush()
		select {
		case <-r.Context().Done():
		case <-release:
		}
	}))
	defer srv.Close()
	defer close(release)

	ctx, cancel := context.WithCancel(context.Background())
	m := NewManager(t.TempDir())
	spec := ModelSpec{ID: "toy", Version: "1", URL: srv.URL, SHA256: "00ff"}
	_, err := m.ensureModel(ctx, spec, func(done, total int64) {
		cancel() // cancel as soon as the first bytes land
	})
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("cancelled download = %v, want context.Canceled", err)
	}
}

func TestEnsureModelNoURL(t *testing.T) {
	m := NewManager(t.TempDir())
	if _, err := m.ensureModel(context.Background(), ModelSpec{ID: "ghost", Version: "1"}, nil); err == nil {
		t.Fatal("expected error for absent model with no URL")
	}
}

func TestInstalledModels(t *testing.T) {
	m := NewManager(filepath.Join(t.TempDir(), "models"))

	// Missing dir (nothing downloaded yet) is empty, not an error.
	got, err := m.InstalledModels()
	if err != nil || len(got) != 0 {
		t.Fatalf("InstalledModels on missing dir = %v, %v; want empty, nil", got, err)
	}

	if err := os.MkdirAll(m.modelsDir, 0o755); err != nil {
		t.Fatal(err)
	}
	for name, size := range map[string]int{"toy-1.onnx": 16, "toy-1.onnx.part-123": 4, "notes.txt": 2} {
		if err := os.WriteFile(filepath.Join(m.modelsDir, name), make([]byte, size), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	got, err = m.InstalledModels()
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 || got[0].FileName != "toy-1.onnx" || got[0].Bytes != 16 {
		t.Fatalf("InstalledModels = %v, want just toy-1.onnx (16 B)", got)
	}
}

func TestDeleteModel(t *testing.T) {
	requireRuntime(t)
	dir := t.TempDir()
	m := NewManager(dir)
	spec := toySpec(t, dir)
	if _, err := m.Session(context.Background(), spec, nil); err != nil {
		t.Fatal(err)
	}

	for _, bad := range []string{"../toy-1.onnx", "toy-1.bin", "sub/toy-1.onnx"} {
		if err := m.DeleteModel(bad); err == nil {
			t.Errorf("DeleteModel(%q) succeeded, want validation error", bad)
		}
	}

	if err := m.DeleteModel(spec.FileName()); err != nil {
		t.Fatal(err)
	}
	if m.HasModel(spec) {
		t.Error("model file still on disk after DeleteModel")
	}
	if _, ok := m.sessions[spec.ID]; ok {
		t.Error("live session not evicted by DeleteModel")
	}

	// A fresh Session must re-materialize the weights, not serve a zombie.
	if _, err := m.Session(context.Background(), spec, nil); err == nil {
		t.Error("Session after delete succeeded without a URL to re-download from")
	}
}

// TestDeleteModelDuringRun deletes a model while a tight Run loop hammers its
// session. destroy() must drain the in-flight pass rather than free the native
// session under it — run with -race; without the mu guard this is a cgo
// use-after-free. After the delete, Run returns the deleted-session error
// instead of crashing.
func TestDeleteModelDuringRun(t *testing.T) {
	requireRuntime(t)
	dir := t.TempDir()
	m := NewManager(dir)
	spec := toySpec(t, dir)
	s, err := m.Session(context.Background(), spec, nil)
	if err != nil {
		t.Fatal(err)
	}

	newTensor := func() *ort.Tensor[float32] {
		in := make([]float32, toyLen)
		tensor, err := ort.NewTensor(ort.NewShape(1, 3, 2, 2), in)
		if err != nil {
			t.Fatal(err)
		}
		return tensor
	}

	stop := make(chan struct{})
	done := make(chan struct{})
	var sawDeleted atomic.Bool
	go func() {
		defer close(done)
		for {
			select {
			case <-stop:
				return
			default:
			}
			tensor := newTensor()
			outs, err := s.Run(context.Background(), tensor)
			tensor.Destroy()
			if err != nil {
				sawDeleted.Store(true) // deleted mid-loop; keep looping safely
				continue
			}
			for _, o := range outs {
				o.Destroy()
			}
		}
	}()

	if err := m.DeleteModel(spec.FileName()); err != nil {
		t.Fatal(err)
	}
	close(stop)
	<-done

	// A Run after the delete must fail cleanly, never crash.
	tensor := newTensor()
	if _, err := s.Run(context.Background(), tensor); err == nil {
		t.Error("Run on a deleted session succeeded, want an error")
	}
	tensor.Destroy()
	if !sawDeleted.Load() {
		t.Log("delete landed after the run loop stopped (still valid: no crash)")
	}
}

// TestDeleteModelOrphanKeepsLiveSession deletes an orphaned old-version file
// whose name shares the live model's id prefix; the live session must survive.
func TestDeleteModelOrphanKeepsLiveSession(t *testing.T) {
	requireRuntime(t)
	dir := t.TempDir()
	m := NewManager(dir)
	spec := toySpec(t, dir) // writes toy-1.onnx, loads the session
	if _, err := m.Session(context.Background(), spec, nil); err != nil {
		t.Fatal(err)
	}
	// An orphaned older version on disk, same id ("toy") prefix.
	orphan := "toy-0.onnx"
	if err := os.WriteFile(filepath.Join(dir, orphan), []byte("stale"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := m.DeleteModel(orphan); err != nil {
		t.Fatal(err)
	}
	if _, ok := m.sessions[spec.ID]; !ok {
		t.Error("deleting the orphan evicted the live current-version session")
	}
	if m.HasModel(spec) == false {
		t.Error("deleting the orphan removed the live model's file")
	}
}

func TestRegistry(t *testing.T) {
	spec := ModelSpec{ID: "reg-test", Version: "1"}
	Register(spec)
	got, ok := Lookup("reg-test")
	if !ok || got.Version != "1" {
		t.Fatalf("Lookup = %v, %v", got, ok)
	}
	defer func() {
		if recover() == nil {
			t.Error("duplicate Register did not panic")
		}
	}()
	Register(spec)
}
