// Code generated by aprot. DO NOT EDIT.
// Shared types from package: api

export const ColorSpace = {
    Srgb: "srgb",
    Adobergb: "adobergb",
    Prophoto: "prophoto",
} as const;
export type ColorSpaceType = typeof ColorSpace[keyof typeof ColorSpace];

export const ExifMode = {
    All: "all",
    Copyright: "copyright",
    None: "none",
} as const;
export type ExifModeType = typeof ExifMode[keyof typeof ExifMode];

export const ExportFormat = {
    Jpeg: "jpeg",
    Tiff8: "tiff8",
    Png: "png",
    RawXmp: "rawXmp",
} as const;
export type ExportFormatType = typeof ExportFormat[keyof typeof ExportFormat];

export const SharpenAmount = {
    Low: "low",
    Standard: "standard",
    High: "high",
} as const;
export type SharpenAmountType = typeof SharpenAmount[keyof typeof SharpenAmount];

export const SharpenTarget = {
    Off: "off",
    Screen: "screen",
    Matte: "matte",
    Glossy: "glossy",
} as const;
export type SharpenTargetType = typeof SharpenTarget[keyof typeof SharpenTarget];

