// Code generated by aprot. DO NOT EDIT.
// Shared types from package: edit

export const Demosaic = {
    Vng: "vng",
    Ppg: "ppg",
    Ahd: "ahd",
    Dht: "dht",
} as const;
export type DemosaicType = typeof Demosaic[keyof typeof Demosaic];

export const WBMode = {
    Camera: "camera",
    Auto: "auto",
    Custom: "custom",
    Kelvin: "kelvin",
} as const;
export type WBModeType = typeof WBMode[keyof typeof WBMode];

export interface Mask {
    type: string;
    invert?: boolean;
    x0?: number;
    y0?: number;
    x1?: number;
    y1?: number;
    cx?: number;
    cy?: number;
    rx?: number;
    ry?: number;
    angle?: number;
    feather?: number;
    strokes?: Stroke[];
    adjust: MaskAdjust;
}

export interface MaskAdjust {
    expEV?: number;
    contrast?: number;
    toneHighlights?: number;
    toneShadows?: number;
    whites?: number;
    blacks?: number;
    temp?: number;
    tint?: number;
    saturation?: number;
}

export interface Params {
    expEV: number;
    expPreserve: number;
    wbMode: WBModeType;
    wbMul: [number, number, number, number];
    wbTemp: number;
    wbTint: number;
    wbKelvin: number;
    bright: number;
    gamma: number;
    shadow: number;
    highlight: number;
    nrThreshold: number;
    fbddNoiseRd: number;
    medPasses: number;
    contrast: number;
    whites: number;
    blacks: number;
    toneShadows: number;
    toneHighlights: number;
    saturation: number;
    vibrance: number;
    splitShadowHue: number;
    splitShadowAmt: number;
    splitHighlightHue: number;
    splitHighlightAmt: number;
    hslHue: [number, number, number, number, number, number, number, number];
    hslSat: [number, number, number, number, number, number, number, number];
    hslLum: [number, number, number, number, number, number, number, number];
    vignette: number;
    texture: number;
    clarity: number;
    dehaze: number;
    sharpen: number;
    demosaic: DemosaicType;
    caRed: number;
    caBlue: number;
    rotate: number;
    flipH: boolean;
    cropX: number;
    cropY: number;
    cropW: number;
    cropH: number;
    cropAngle: number;
    masks?: Mask[];
}

export interface Stroke {
    erase?: boolean;
    radius: number;
    feather?: number;
    flow?: number;
    pts: number[];
}

