// Code generated by aprot. DO NOT EDIT.
import { z } from 'zod';

export const ParamsSchema = z.object({
    expEV: z.number().min(-2).max(3),
    expPreserve: z.number().min(0).max(1),
    wbMode: z.union([z.literal(""), z.enum(["camera", "auto", "custom", "kelvin"])]),
    wbMul: z.tuple([z.number(), z.number(), z.number(), z.number()]),
    wbTemp: z.number().min(-1).max(1),
    wbTint: z.number().min(-1).max(1),
    wbKelvin: z.number().min(1700).max(25000),
    bright: z.number().min(0).max(4),
    gamma: z.number().min(0).max(3.5),
    shadow: z.number().min(0).max(12),
    highlight: z.number().int().min(0).max(9),
    nrThreshold: z.number().min(0).max(1000),
    fbddNoiseRd: z.number().int().min(0).max(2),
    medPasses: z.number().int().min(0).max(5),
    contrast: z.number().min(-1).max(1),
    whites: z.number().min(-1).max(1),
    blacks: z.number().min(-1).max(1),
    toneShadows: z.number().min(-1).max(1),
    toneHighlights: z.number().min(-1).max(1),
    saturation: z.number().min(-1).max(1),
    vibrance: z.number().min(-1).max(1),
    splitShadowHue: z.number().min(0).lt(360),
    splitShadowAmt: z.number().min(0).max(1),
    splitHighlightHue: z.number().min(0).lt(360),
    splitHighlightAmt: z.number().min(0).max(1),
    vignette: z.number().min(-1).max(1),
    demosaic: z.union([z.literal(""), z.enum(["vng", "ppg", "ahd", "dht"])]),
    caRed: z.number().min(-1).max(1),
    caBlue: z.number().min(-1).max(1),
});

export type Params = z.infer<typeof ParamsSchema>;
