// Code generated by aprot. DO NOT EDIT.
import { z } from 'zod';

export const ParamsSchema = z.object({
    expEV: z.number().min(-2).max(3),
    expPreserve: z.number().min(0).max(1),
    wbMode: z.union([z.literal(""), z.enum(["camera", "auto", "custom"])]),
    wbMul: z.tuple([z.number(), z.number(), z.number(), z.number()]),
    wbTemp: z.number().min(-1).max(1),
    wbTint: z.number().min(-1).max(1),
    bright: z.number().min(0).max(4),
    gamma: z.number().min(0).max(3.5),
    shadow: z.number().min(0).max(12),
    highlight: z.number().int().min(0).max(9),
    nrThreshold: z.number().min(0).max(1000),
    fbddNoiseRd: z.number().int().min(0).max(2),
    medPasses: z.number().int().min(0).max(5),
});

export type Params = z.infer<typeof ParamsSchema>;
