// Code generated by aprot. DO NOT EDIT.
// Handler: Edits
import { useCallback } from 'react';
import { ApiClient, useQuery } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
} from './client';
import type { AIKindType, Params } from './edit';
import type { TaskRef } from './tasks';

export interface AICategory {
    id: number;
    name: string;
    fraction: number;
}

export interface AIMapResult {
    mapVer: string;
    generated: boolean;
    categories?: AICategory[];
}

export interface AIModelInfo {
    downloaded: boolean;
    bytes: number;
}

export interface Delta {
    expEV: number | null;
    bright: number | null;
    highlight: number | null;
    nrThreshold: number | null;
    fbddNoiseRd: number | null;
    medPasses: number | null;
    contrast: number | null;
    whites: number | null;
    blacks: number | null;
    toneShadows: number | null;
    toneHighlights: number | null;
    saturation: number | null;
    vibrance: number | null;
}


export function aIModelStatus(client: ApiClient, kind: AIKindType, options?: RequestOptions): Promise<AIModelInfo> {
    return client.request<AIModelInfo>('Edits.AIModelStatus', [kind], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
aIModelStatus.method = 'Edits.AIModelStatus' as const;

export function subscribeAIModelStatus(client: ApiClient, kind: AIKindType, callback: (data: AIModelInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<AIModelInfo>('Edits.AIModelStatus', [kind], callback, onError, options);
}


export function analyzeSubjects(client: ApiClient, photoIDs: number[], allowDownload: boolean, options?: RequestOptions): Promise<TaskRef> {
    return client.request<TaskRef>('Edits.AnalyzeSubjects', [photoIDs, allowDownload], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
analyzeSubjects.method = 'Edits.AnalyzeSubjects' as const;

export function subscribeAnalyzeSubjects(client: ApiClient, photoIDs: number[], allowDownload: boolean, callback: (data: TaskRef) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<TaskRef>('Edits.AnalyzeSubjects', [photoIDs, allowDownload], callback, onError, options);
}


export function applyBatchEdit(client: ApiClient, ids: number[], delta: Delta, options?: RequestOptions): Promise<void> {
    return client.request<void>('Edits.ApplyBatchEdit', [ids, delta], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
applyBatchEdit.method = 'Edits.ApplyBatchEdit' as const;

export function subscribeApplyBatchEdit(client: ApiClient, ids: number[], delta: Delta, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Edits.ApplyBatchEdit', [ids, delta], callback, onError, options);
}


export function autoAdjust(client: ApiClient, photoID: number, params: Params, sections: string[], options?: RequestOptions): Promise<Params> {
    return client.request<Params>('Edits.AutoAdjust', [photoID, params, sections], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
autoAdjust.method = 'Edits.AutoAdjust' as const;

export function subscribeAutoAdjust(client: ApiClient, photoID: number, params: Params, sections: string[], callback: (data: Params) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Params>('Edits.AutoAdjust', [photoID, params, sections], callback, onError, options);
}


export function generateAIMap(client: ApiClient, photoID: number, kind: AIKindType, allowDownload: boolean, options?: RequestOptions): Promise<AIMapResult> {
    return client.request<AIMapResult>('Edits.GenerateAIMap', [photoID, kind, allowDownload], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
generateAIMap.method = 'Edits.GenerateAIMap' as const;

export function subscribeGenerateAIMap(client: ApiClient, photoID: number, kind: AIKindType, allowDownload: boolean, callback: (data: AIMapResult) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<AIMapResult>('Edits.GenerateAIMap', [photoID, kind, allowDownload], callback, onError, options);
}


export function getEditParams(client: ApiClient, photoID: number, options?: RequestOptions): Promise<Params> {
    return client.request<Params>('Edits.GetEditParams', [photoID], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
getEditParams.method = 'Edits.GetEditParams' as const;

export function subscribeGetEditParams(client: ApiClient, photoID: number, callback: (data: Params) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Params>('Edits.GetEditParams', [photoID], callback, onError, options);
}


export function maskTintPreview(client: ApiClient, photoID: number, params: Params, maskIndex: number, longEdge: number, options?: RequestOptions): Promise<Blob> {
    return client.request<Blob>('Edits.MaskTintPreview', [photoID, params, maskIndex, longEdge], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
maskTintPreview.method = 'Edits.MaskTintPreview' as const;

export function subscribeMaskTintPreview(client: ApiClient, photoID: number, params: Params, maskIndex: number, longEdge: number, callback: (data: Blob) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Blob>('Edits.MaskTintPreview', [photoID, params, maskIndex, longEdge], callback, onError, options);
}


export function pasteEditParams(client: ApiClient, ids: number[], params: Params, options?: RequestOptions): Promise<void> {
    return client.request<void>('Edits.PasteEditParams', [ids, params], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
pasteEditParams.method = 'Edits.PasteEditParams' as const;

export function subscribePasteEditParams(client: ApiClient, ids: number[], params: Params, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Edits.PasteEditParams', [ids, params], callback, onError, options);
}


export function pickWhiteBalance(client: ApiClient, photoID: number, params: Params, x: number, y: number, options?: RequestOptions): Promise<Params> {
    return client.request<Params>('Edits.PickWhiteBalance', [photoID, params, x, y], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
pickWhiteBalance.method = 'Edits.PickWhiteBalance' as const;

export function subscribePickWhiteBalance(client: ApiClient, photoID: number, params: Params, x: number, y: number, callback: (data: Params) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Params>('Edits.PickWhiteBalance', [photoID, params, x, y], callback, onError, options);
}


export function previewEdit(client: ApiClient, photoID: number, params: Params, longEdge: number, options?: RequestOptions): Promise<Blob> {
    return client.request<Blob>('Edits.PreviewEdit', [photoID, params, longEdge], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
previewEdit.method = 'Edits.PreviewEdit' as const;

export function subscribePreviewEdit(client: ApiClient, photoID: number, params: Params, longEdge: number, callback: (data: Blob) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Blob>('Edits.PreviewEdit', [photoID, params, longEdge], callback, onError, options);
}


export function resetEdits(client: ApiClient, ids: number[], options?: RequestOptions): Promise<void> {
    return client.request<void>('Edits.ResetEdits', [ids], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
resetEdits.method = 'Edits.ResetEdits' as const;

export function subscribeResetEdits(client: ApiClient, ids: number[], callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Edits.ResetEdits', [ids], callback, onError, options);
}


export function setEditParams(client: ApiClient, photoID: number, params: Params, options?: RequestOptions): Promise<void> {
    return client.request<void>('Edits.SetEditParams', [photoID, params], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setEditParams.method = 'Edits.SetEditParams' as const;

export function subscribeSetEditParams(client: ApiClient, photoID: number, params: Params, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Edits.SetEditParams', [photoID, params], callback, onError, options);
}

// React Hooks for Edits

/**
 * Subscribes to `Edits.AIModelStatus` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useAIModelStatus(kind: AIKindType, options?: UseQueryOptions<AIModelInfo>): UseQueryResult<AIModelInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, kind: AIKindType) => aIModelStatus(client, kind, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [kind], _subscribe: { method: 'Edits.AIModelStatus', params: [kind] } });
}

/**
 * Subscribes to `Edits.AnalyzeSubjects` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useAnalyzeSubjects(photoIDs: number[], allowDownload: boolean, options?: UseQueryOptions<TaskRef>): UseQueryResult<TaskRef> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoIDs: number[], allowDownload: boolean) => analyzeSubjects(client, photoIDs, allowDownload, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoIDs, allowDownload], _subscribe: { method: 'Edits.AnalyzeSubjects', params: [photoIDs, allowDownload] } });
}

/**
 * Subscribes to `Edits.ApplyBatchEdit` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useApplyBatchEdit(ids: number[], delta: Delta, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, ids: number[], delta: Delta) => applyBatchEdit(client, ids, delta, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [ids, delta], _subscribe: { method: 'Edits.ApplyBatchEdit', params: [ids, delta] } });
}

/**
 * Subscribes to `Edits.AutoAdjust` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useAutoAdjust(photoID: number, params: Params, sections: string[], options?: UseQueryOptions<Params>): UseQueryResult<Params> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number, params: Params, sections: string[]) => autoAdjust(client, photoID, params, sections, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID, params, sections], _subscribe: { method: 'Edits.AutoAdjust', params: [photoID, params, sections] } });
}

/**
 * Subscribes to `Edits.GenerateAIMap` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useGenerateAIMap(photoID: number, kind: AIKindType, allowDownload: boolean, options?: UseQueryOptions<AIMapResult>): UseQueryResult<AIMapResult> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number, kind: AIKindType, allowDownload: boolean) => generateAIMap(client, photoID, kind, allowDownload, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID, kind, allowDownload], _subscribe: { method: 'Edits.GenerateAIMap', params: [photoID, kind, allowDownload] } });
}

/**
 * Subscribes to `Edits.GetEditParams` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useGetEditParams(photoID: number, options?: UseQueryOptions<Params>): UseQueryResult<Params> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number) => getEditParams(client, photoID, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID], _subscribe: { method: 'Edits.GetEditParams', params: [photoID] } });
}

/**
 * Subscribes to `Edits.MaskTintPreview` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useMaskTintPreview(photoID: number, params: Params, maskIndex: number, longEdge: number, options?: UseQueryOptions<Blob>): UseQueryResult<Blob> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number, params: Params, maskIndex: number, longEdge: number) => maskTintPreview(client, photoID, params, maskIndex, longEdge, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID, params, maskIndex, longEdge], _subscribe: { method: 'Edits.MaskTintPreview', params: [photoID, params, maskIndex, longEdge] } });
}

/**
 * Subscribes to `Edits.PasteEditParams` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function usePasteEditParams(ids: number[], params: Params, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, ids: number[], params: Params) => pasteEditParams(client, ids, params, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [ids, params], _subscribe: { method: 'Edits.PasteEditParams', params: [ids, params] } });
}

/**
 * Subscribes to `Edits.PickWhiteBalance` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function usePickWhiteBalance(photoID: number, params: Params, x: number, y: number, options?: UseQueryOptions<Params>): UseQueryResult<Params> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number, params: Params, x: number, y: number) => pickWhiteBalance(client, photoID, params, x, y, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID, params, x, y], _subscribe: { method: 'Edits.PickWhiteBalance', params: [photoID, params, x, y] } });
}

/**
 * Subscribes to `Edits.PreviewEdit` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function usePreviewEdit(photoID: number, params: Params, longEdge: number, options?: UseQueryOptions<Blob>): UseQueryResult<Blob> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number, params: Params, longEdge: number) => previewEdit(client, photoID, params, longEdge, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID, params, longEdge], _subscribe: { method: 'Edits.PreviewEdit', params: [photoID, params, longEdge] } });
}

/**
 * Subscribes to `Edits.ResetEdits` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useResetEdits(ids: number[], options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, ids: number[]) => resetEdits(client, ids, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [ids], _subscribe: { method: 'Edits.ResetEdits', params: [ids] } });
}

/**
 * Subscribes to `Edits.SetEditParams` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetEditParams(photoID: number, params: Params, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number, params: Params) => setEditParams(client, photoID, params, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID, params], _subscribe: { method: 'Edits.SetEditParams', params: [photoID, params] } });
}
