// Code generated by aprot. DO NOT EDIT.
// Handler: Edits
import { useCallback } from 'react';
import { ApiClient, useQuery } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
} from './client';

export const Demosaic = {
    Vng: "vng",
    Ppg: "ppg",
    Ahd: "ahd",
    Dht: "dht",
} as const;
export type DemosaicType = typeof Demosaic[keyof typeof Demosaic];

export const WBMode = {
    Camera: "camera",
    Auto: "auto",
    Custom: "custom",
    Kelvin: "kelvin",
} as const;
export type WBModeType = typeof WBMode[keyof typeof WBMode];

export interface Delta {
    expEV: number | null;
    bright: number | null;
    highlight: number | null;
    nrThreshold: number | null;
    fbddNoiseRd: number | null;
    medPasses: number | null;
    contrast: number | null;
    whites: number | null;
    blacks: number | null;
    toneShadows: number | null;
    toneHighlights: number | null;
    saturation: number | null;
    vibrance: number | null;
}

export interface Params {
    expEV: number;
    expPreserve: number;
    wbMode: WBModeType;
    wbMul: [number, number, number, number];
    wbTemp: number;
    wbTint: number;
    wbKelvin: number;
    bright: number;
    gamma: number;
    shadow: number;
    highlight: number;
    nrThreshold: number;
    fbddNoiseRd: number;
    medPasses: number;
    contrast: number;
    whites: number;
    blacks: number;
    toneShadows: number;
    toneHighlights: number;
    saturation: number;
    vibrance: number;
    splitShadowHue: number;
    splitShadowAmt: number;
    splitHighlightHue: number;
    splitHighlightAmt: number;
    vignette: number;
    texture: number;
    clarity: number;
    dehaze: number;
    sharpen: number;
    demosaic: DemosaicType;
    caRed: number;
    caBlue: number;
    cropX: number;
    cropY: number;
    cropW: number;
    cropH: number;
    cropAngle: number;
}


export function applyBatchEdit(client: ApiClient, ids: number[], delta: Delta, options?: RequestOptions): Promise<void> {
    return client.request<void>('Edits.ApplyBatchEdit', [ids, delta], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
applyBatchEdit.method = 'Edits.ApplyBatchEdit' as const;

export function subscribeApplyBatchEdit(client: ApiClient, ids: number[], delta: Delta, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Edits.ApplyBatchEdit', [ids, delta], callback, onError, options);
}


export function autoAdjust(client: ApiClient, photoID: number, params: Params, sections: string[], options?: RequestOptions): Promise<Params> {
    return client.request<Params>('Edits.AutoAdjust', [photoID, params, sections], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
autoAdjust.method = 'Edits.AutoAdjust' as const;

export function subscribeAutoAdjust(client: ApiClient, photoID: number, params: Params, sections: string[], callback: (data: Params) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Params>('Edits.AutoAdjust', [photoID, params, sections], callback, onError, options);
}


export function getEditParams(client: ApiClient, photoID: number, options?: RequestOptions): Promise<Params> {
    return client.request<Params>('Edits.GetEditParams', [photoID], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
getEditParams.method = 'Edits.GetEditParams' as const;

export function subscribeGetEditParams(client: ApiClient, photoID: number, callback: (data: Params) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Params>('Edits.GetEditParams', [photoID], callback, onError, options);
}


export function pasteEditParams(client: ApiClient, ids: number[], params: Params, options?: RequestOptions): Promise<void> {
    return client.request<void>('Edits.PasteEditParams', [ids, params], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
pasteEditParams.method = 'Edits.PasteEditParams' as const;

export function subscribePasteEditParams(client: ApiClient, ids: number[], params: Params, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Edits.PasteEditParams', [ids, params], callback, onError, options);
}


export function pickWhiteBalance(client: ApiClient, photoID: number, params: Params, x: number, y: number, options?: RequestOptions): Promise<Params> {
    return client.request<Params>('Edits.PickWhiteBalance', [photoID, params, x, y], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
pickWhiteBalance.method = 'Edits.PickWhiteBalance' as const;

export function subscribePickWhiteBalance(client: ApiClient, photoID: number, params: Params, x: number, y: number, callback: (data: Params) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Params>('Edits.PickWhiteBalance', [photoID, params, x, y], callback, onError, options);
}


export function previewEdit(client: ApiClient, photoID: number, params: Params, longEdge: number, options?: RequestOptions): Promise<Blob> {
    return client.request<Blob>('Edits.PreviewEdit', [photoID, params, longEdge], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
previewEdit.method = 'Edits.PreviewEdit' as const;

export function subscribePreviewEdit(client: ApiClient, photoID: number, params: Params, longEdge: number, callback: (data: Blob) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Blob>('Edits.PreviewEdit', [photoID, params, longEdge], callback, onError, options);
}


export function resetEdits(client: ApiClient, ids: number[], options?: RequestOptions): Promise<void> {
    return client.request<void>('Edits.ResetEdits', [ids], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
resetEdits.method = 'Edits.ResetEdits' as const;

export function subscribeResetEdits(client: ApiClient, ids: number[], callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Edits.ResetEdits', [ids], callback, onError, options);
}


export function setEditParams(client: ApiClient, photoID: number, params: Params, options?: RequestOptions): Promise<void> {
    return client.request<void>('Edits.SetEditParams', [photoID, params], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setEditParams.method = 'Edits.SetEditParams' as const;

export function subscribeSetEditParams(client: ApiClient, photoID: number, params: Params, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Edits.SetEditParams', [photoID, params], callback, onError, options);
}

// React Hooks for Edits

/**
 * Subscribes to `Edits.ApplyBatchEdit` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useApplyBatchEdit(ids: number[], delta: Delta, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, ids: number[], delta: Delta) => applyBatchEdit(client, ids, delta, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [ids, delta], _subscribe: { method: 'Edits.ApplyBatchEdit', params: [ids, delta] } });
}

/**
 * Subscribes to `Edits.AutoAdjust` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useAutoAdjust(photoID: number, params: Params, sections: string[], options?: UseQueryOptions<Params>): UseQueryResult<Params> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number, params: Params, sections: string[]) => autoAdjust(client, photoID, params, sections, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID, params, sections], _subscribe: { method: 'Edits.AutoAdjust', params: [photoID, params, sections] } });
}

/**
 * Subscribes to `Edits.GetEditParams` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useGetEditParams(photoID: number, options?: UseQueryOptions<Params>): UseQueryResult<Params> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number) => getEditParams(client, photoID, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID], _subscribe: { method: 'Edits.GetEditParams', params: [photoID] } });
}

/**
 * Subscribes to `Edits.PasteEditParams` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function usePasteEditParams(ids: number[], params: Params, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, ids: number[], params: Params) => pasteEditParams(client, ids, params, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [ids, params], _subscribe: { method: 'Edits.PasteEditParams', params: [ids, params] } });
}

/**
 * Subscribes to `Edits.PickWhiteBalance` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function usePickWhiteBalance(photoID: number, params: Params, x: number, y: number, options?: UseQueryOptions<Params>): UseQueryResult<Params> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number, params: Params, x: number, y: number) => pickWhiteBalance(client, photoID, params, x, y, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID, params, x, y], _subscribe: { method: 'Edits.PickWhiteBalance', params: [photoID, params, x, y] } });
}

/**
 * Subscribes to `Edits.PreviewEdit` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function usePreviewEdit(photoID: number, params: Params, longEdge: number, options?: UseQueryOptions<Blob>): UseQueryResult<Blob> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number, params: Params, longEdge: number) => previewEdit(client, photoID, params, longEdge, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID, params, longEdge], _subscribe: { method: 'Edits.PreviewEdit', params: [photoID, params, longEdge] } });
}

/**
 * Subscribes to `Edits.ResetEdits` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useResetEdits(ids: number[], options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, ids: number[]) => resetEdits(client, ids, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [ids], _subscribe: { method: 'Edits.ResetEdits', params: [ids] } });
}

/**
 * Subscribes to `Edits.SetEditParams` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetEditParams(photoID: number, params: Params, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, photoID: number, params: Params) => setEditParams(client, photoID, params, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [photoID, params], _subscribe: { method: 'Edits.SetEditParams', params: [photoID, params] } });
}
