// Code generated by aprot. DO NOT EDIT.
import { z } from 'zod';

export const ExportRequestSchema = z.object({
    photoIds: z.array(z.number().int()).min(1),
    destDir: z.string().min(1),
    format: z.enum(["jpeg", "tiff16"]),
    jpegQuality: z.number().int().min(0).max(100),
    longEdge: z.number().int().min(0).max(65536),
    createDir: z.boolean(),
});

export type ExportRequest = z.infer<typeof ExportRequestSchema>;
