// Code generated by aprot. DO NOT EDIT.
// Handler: Export
import { useCallback } from 'react';
import { ApiClient, useStream } from './client';
import type {
    RequestOptions,
    UseStreamOptions,
    UseStreamResult,
} from './client';

export const ExportFormat = {
    Jpeg: "jpeg",
    Tiff16: "tiff16",
} as const;
export type ExportFormatType = typeof ExportFormat[keyof typeof ExportFormat];

export interface ExportItem {
    photoId: number;
    fileName: string;
    ok: boolean;
    error: string;
}

export interface ExportRequest {
    photoIds: number[];
    destDir: string;
    format: ExportFormatType;
    jpegQuality: number;
    longEdge: number;
}


export function exportPhotos(client: ApiClient, req: ExportRequest, options?: RequestOptions): AsyncIterable<ExportItem> {
    return client.requestStream<ExportItem>('Export.ExportPhotos', [req], options);
}

// React Hooks for Export

/**
 * Streams items from `Export.ExportPhotos` and accumulates them into `items`.
 * The stream restarts when parameters change and cleans up on unmount.
 * See {@link UseStreamResult} for return value details.
 */
export function useExportPhotos(req: ExportRequest, options?: UseStreamOptions): UseStreamResult<ExportItem> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, req: ExportRequest) => exportPhotos(client, req, { signal }),
        [],
    );
    return useStream(wrappedFn, { ...(options ?? {}), params: [req] as [ExportRequest] });
}
