// Code generated by aprot. DO NOT EDIT.
// Handler: Export
import { useCallback } from 'react';
import { ApiClient, useQuery } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
} from './client';
import type { ColorSpaceType, ExifModeType, ExportFormatType, SharpenAmountType, SharpenTargetType } from './api';

export interface DestInfo {
    exists: boolean;
}

export interface ExportRequest {
    photoIds: number[];
    destDir: string;
    format: ExportFormatType;
    jpegQuality: number;
    longEdge: number;
    colorSpace: ColorSpaceType;
    sharpenTarget: SharpenTargetType;
    sharpenAmount: SharpenAmountType;
    fileNameTemplate: string;
    exifMode: ExifModeType;
    removeLocation: boolean;
    artist: string;
    copyright: string;
    watermarkId: string;
    createDir: boolean;
}

export interface TaskRef {
    taskId: string;
}


export function checkDest(client: ApiClient, path: string, options?: RequestOptions): Promise<DestInfo> {
    return client.request<DestInfo>('Export.CheckDest', [path], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
checkDest.method = 'Export.CheckDest' as const;

export function subscribeCheckDest(client: ApiClient, path: string, callback: (data: DestInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<DestInfo>('Export.CheckDest', [path], callback, onError, options);
}


export function startExport(client: ApiClient, req: ExportRequest, options?: RequestOptions): Promise<TaskRef> {
    return client.request<TaskRef>('Export.StartExport', [req], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
startExport.method = 'Export.StartExport' as const;

export function subscribeStartExport(client: ApiClient, req: ExportRequest, callback: (data: TaskRef) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<TaskRef>('Export.StartExport', [req], callback, onError, options);
}

// React Hooks for Export

/**
 * Subscribes to `Export.CheckDest` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useCheckDest(path: string, options?: UseQueryOptions<DestInfo>): UseQueryResult<DestInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, path: string) => checkDest(client, path, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [path], _subscribe: { method: 'Export.CheckDest', params: [path] } });
}

/**
 * Subscribes to `Export.StartExport` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useStartExport(req: ExportRequest, options?: UseQueryOptions<TaskRef>): UseQueryResult<TaskRef> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, req: ExportRequest) => startExport(client, req, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [req], _subscribe: { method: 'Export.StartExport', params: [req] } });
}
