// Code generated by aprot. DO NOT EDIT.
// Handler: Library
import { useCallback } from 'react';
import { ApiClient, useQuery, usePushEvent } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
    PushHandler,
    UsePushResult,
} from './client';

export const Flag = {
    None: "none",
    Pick: "pick",
    Exclude: "exclude",
} as const;
export type FlagType = typeof Flag[keyof typeof Flag];

export interface AppSettings {
    sidecarWrites: boolean;
}

export interface DeleteResult {
    deleted: number;
}

export interface DirEntry {
    name: string;
    path: string;
    hasSubdirs: boolean;
}

export interface DriveInfo {
    path: string;
    name: string;
}

export interface FolderInfo {
    folderId: number;
    path: string;
    photoCount: number;
}

export interface FolderPrefs {
    favorites: string[];
    recents: string[];
}

export interface Photo {
    id: number;
    fileName: string;
    cacheKey: string;
    editHash: string;
    rating: number;
    flag: FlagType;
    metaLoaded: boolean;
    width: number;
    height: number;
    orientation: number;
    iso: number;
    shutter: number;
    aperture: number;
    focalLen: number;
    takenAt: number;
    make: string;
    model: string;
}

export interface PhotoPatch {
    id: number;
    rating: number | null;
    flag: FlagType | null;
    editHash: string | null;
}

export interface PhotoPatchEvent {
    patches: PhotoPatch[];
}


export function deletePhotos(client: ApiClient, ids: number[], options?: RequestOptions): Promise<DeleteResult> {
    return client.request<DeleteResult>('Library.DeletePhotos', [ids], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
deletePhotos.method = 'Library.DeletePhotos' as const;

export function subscribeDeletePhotos(client: ApiClient, ids: number[], callback: (data: DeleteResult) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<DeleteResult>('Library.DeletePhotos', [ids], callback, onError, options);
}


export function getAppSettings(client: ApiClient, options?: RequestOptions): Promise<AppSettings> {
    return client.request<AppSettings>('Library.GetAppSettings', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
getAppSettings.method = 'Library.GetAppSettings' as const;

export function subscribeGetAppSettings(client: ApiClient, callback: (data: AppSettings) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<AppSettings>('Library.GetAppSettings', [], callback, onError, options);
}


export function getFolderPrefs(client: ApiClient, options?: RequestOptions): Promise<FolderPrefs> {
    return client.request<FolderPrefs>('Library.GetFolderPrefs', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
getFolderPrefs.method = 'Library.GetFolderPrefs' as const;

export function subscribeGetFolderPrefs(client: ApiClient, callback: (data: FolderPrefs) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<FolderPrefs>('Library.GetFolderPrefs', [], callback, onError, options);
}


export function listDir(client: ApiClient, path: string, options?: RequestOptions): Promise<DirEntry[]> {
    return client.request<DirEntry[]>('Library.ListDir', [path], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
listDir.method = 'Library.ListDir' as const;

export function subscribeListDir(client: ApiClient, path: string, callback: (data: DirEntry[]) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<DirEntry[]>('Library.ListDir', [path], callback, onError, options);
}


export function listDrives(client: ApiClient, options?: RequestOptions): Promise<DriveInfo[]> {
    return client.request<DriveInfo[]>('Library.ListDrives', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
listDrives.method = 'Library.ListDrives' as const;

export function subscribeListDrives(client: ApiClient, callback: (data: DriveInfo[]) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<DriveInfo[]>('Library.ListDrives', [], callback, onError, options);
}


export function listPhotos(client: ApiClient, folderID: number, options?: RequestOptions): Promise<Photo[]> {
    return client.request<Photo[]>('Library.ListPhotos', [folderID], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
listPhotos.method = 'Library.ListPhotos' as const;

export function subscribeListPhotos(client: ApiClient, folderID: number, callback: (data: Photo[]) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<Photo[]>('Library.ListPhotos', [folderID], callback, onError, options);
}


export function openFolder(client: ApiClient, path: string, options?: RequestOptions): Promise<FolderInfo> {
    return client.request<FolderInfo>('Library.OpenFolder', [path], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
openFolder.method = 'Library.OpenFolder' as const;

export function subscribeOpenFolder(client: ApiClient, path: string, callback: (data: FolderInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<FolderInfo>('Library.OpenFolder', [path], callback, onError, options);
}


export function setFavoriteFolders(client: ApiClient, paths: string[], options?: RequestOptions): Promise<void> {
    return client.request<void>('Library.SetFavoriteFolders', [paths], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setFavoriteFolders.method = 'Library.SetFavoriteFolders' as const;

export function subscribeSetFavoriteFolders(client: ApiClient, paths: string[], callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Library.SetFavoriteFolders', [paths], callback, onError, options);
}


export function setFlag(client: ApiClient, ids: number[], flag: FlagType, options?: RequestOptions): Promise<void> {
    return client.request<void>('Library.SetFlag', [ids, flag], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setFlag.method = 'Library.SetFlag' as const;

export function subscribeSetFlag(client: ApiClient, ids: number[], flag: FlagType, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Library.SetFlag', [ids, flag], callback, onError, options);
}


export function setRating(client: ApiClient, ids: number[], rating: number, options?: RequestOptions): Promise<void> {
    return client.request<void>('Library.SetRating', [ids, rating], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setRating.method = 'Library.SetRating' as const;

export function subscribeSetRating(client: ApiClient, ids: number[], rating: number, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Library.SetRating', [ids, rating], callback, onError, options);
}


export function setSidecarWrites(client: ApiClient, enabled: boolean, options?: RequestOptions): Promise<void> {
    return client.request<void>('Library.SetSidecarWrites', [enabled], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setSidecarWrites.method = 'Library.SetSidecarWrites' as const;

export function subscribeSetSidecarWrites(client: ApiClient, enabled: boolean, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Library.SetSidecarWrites', [enabled], callback, onError, options);
}


export function setVisible(client: ApiClient, folderID: number, ids: number[], options?: RequestOptions): Promise<void> {
    return client.request<void>('Library.SetVisible', [folderID, ids], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setVisible.method = 'Library.SetVisible' as const;

export function subscribeSetVisible(client: ApiClient, folderID: number, ids: number[], callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Library.SetVisible', [folderID, ids], callback, onError, options);
}

export function onPhotoPatchEvent(client: ApiClient, handler: PushHandler<PhotoPatchEvent>): () => void {
    return client.onPush<PhotoPatchEvent>('PhotoPatchEvent', handler);
}

// React Hooks for Library

/**
 * Subscribes to `Library.DeletePhotos` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useDeletePhotos(ids: number[], options?: UseQueryOptions<DeleteResult>): UseQueryResult<DeleteResult> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, ids: number[]) => deletePhotos(client, ids, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [ids], _subscribe: { method: 'Library.DeletePhotos', params: [ids] } });
}

/**
 * Subscribes to `Library.GetAppSettings` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useGetAppSettings(options?: UseQueryOptions<AppSettings>): UseQueryResult<AppSettings> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => getAppSettings(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'Library.GetAppSettings', params: [] } });
}

/**
 * Subscribes to `Library.GetFolderPrefs` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useGetFolderPrefs(options?: UseQueryOptions<FolderPrefs>): UseQueryResult<FolderPrefs> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => getFolderPrefs(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'Library.GetFolderPrefs', params: [] } });
}

/**
 * Subscribes to `Library.ListDir` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useListDir(path: string, options?: UseQueryOptions<DirEntry[]>): UseQueryResult<DirEntry[]> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, path: string) => listDir(client, path, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [path], _subscribe: { method: 'Library.ListDir', params: [path] } });
}

/**
 * Subscribes to `Library.ListDrives` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useListDrives(options?: UseQueryOptions<DriveInfo[]>): UseQueryResult<DriveInfo[]> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => listDrives(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'Library.ListDrives', params: [] } });
}

/**
 * Subscribes to `Library.ListPhotos` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useListPhotos(folderID: number, options?: UseQueryOptions<Photo[]>): UseQueryResult<Photo[]> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, folderID: number) => listPhotos(client, folderID, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [folderID], _subscribe: { method: 'Library.ListPhotos', params: [folderID] } });
}

/**
 * Subscribes to `Library.OpenFolder` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useOpenFolder(path: string, options?: UseQueryOptions<FolderInfo>): UseQueryResult<FolderInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, path: string) => openFolder(client, path, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [path], _subscribe: { method: 'Library.OpenFolder', params: [path] } });
}

/**
 * Subscribes to `Library.SetFavoriteFolders` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetFavoriteFolders(paths: string[], options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, paths: string[]) => setFavoriteFolders(client, paths, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [paths], _subscribe: { method: 'Library.SetFavoriteFolders', params: [paths] } });
}

/**
 * Subscribes to `Library.SetFlag` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetFlag(ids: number[], flag: FlagType, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, ids: number[], flag: FlagType) => setFlag(client, ids, flag, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [ids, flag], _subscribe: { method: 'Library.SetFlag', params: [ids, flag] } });
}

/**
 * Subscribes to `Library.SetRating` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetRating(ids: number[], rating: number, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, ids: number[], rating: number) => setRating(client, ids, rating, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [ids, rating], _subscribe: { method: 'Library.SetRating', params: [ids, rating] } });
}

/**
 * Subscribes to `Library.SetSidecarWrites` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetSidecarWrites(enabled: boolean, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, enabled: boolean) => setSidecarWrites(client, enabled, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [enabled], _subscribe: { method: 'Library.SetSidecarWrites', params: [enabled] } });
}

/**
 * Subscribes to `Library.SetVisible` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetVisible(folderID: number, ids: number[], options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, folderID: number, ids: number[]) => setVisible(client, folderID, ids, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [folderID, ids], _subscribe: { method: 'Library.SetVisible', params: [folderID, ids] } });
}

export function usePhotoPatchEvent(options?: { maxEvents?: number }): UsePushResult<PhotoPatchEvent> {
    return usePushEvent(onPhotoPatchEvent, options);
}
