// Code generated by aprot. DO NOT EDIT.
// Handler: Settings
import { useCallback } from 'react';
import { ApiClient, useQuery } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
} from './client';
import type { ColorSpaceType, ExportFormatType, SharpenAmountType, SharpenTargetType } from './api';

export const Theme = {
    Dark: "dark",
    Light: "light",
    System: "system",
} as const;
export type ThemeType = typeof Theme[keyof typeof Theme];

export const ThumbFit = {
    Crop: "crop",
    Fit: "fit",
    Natural: "natural",
} as const;
export type ThumbFitType = typeof ThumbFit[keyof typeof ThumbFit];

export interface AutoPreset {
    id: string;
    name: string;
    sections: string[];
    offsets: Record<string, number>;
}

export interface ExportOptions {
    format: ExportFormatType;
    jpegQuality: number;
    resizeMode: string;
    edgePx: number;
    colorSpace: ColorSpaceType;
    sharpenTarget: SharpenTargetType;
    sharpenAmount: SharpenAmountType;
}

export interface UISettings {
    theme: ThemeType;
    gapMinutes: number;
    cullDials: string[];
    quickDials: string[];
    autoPresets: AutoPreset[];
    exportDir: string;
    exportOptions: ExportOptions;
    developPinned: boolean;
    editGroups: Record<string, boolean>;
    groupAliases: Record<string, string>;
    railGroups: Record<string, boolean>;
    railWidth: number;
    prerenderFullres: boolean;
    thumbFit: ThumbFitType;
}


export function getUISettings(client: ApiClient, options?: RequestOptions): Promise<UISettings> {
    return client.request<UISettings>('Settings.GetUISettings', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
getUISettings.method = 'Settings.GetUISettings' as const;

export function subscribeGetUISettings(client: ApiClient, callback: (data: UISettings) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<UISettings>('Settings.GetUISettings', [], callback, onError, options);
}


export function setAutoPresets(client: ApiClient, presets: AutoPreset[], options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetAutoPresets', [presets], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setAutoPresets.method = 'Settings.SetAutoPresets' as const;

export function subscribeSetAutoPresets(client: ApiClient, presets: AutoPreset[], callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetAutoPresets', [presets], callback, onError, options);
}


export function setCullDials(client: ApiClient, dials: string[], options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetCullDials', [dials], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setCullDials.method = 'Settings.SetCullDials' as const;

export function subscribeSetCullDials(client: ApiClient, dials: string[], callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetCullDials', [dials], callback, onError, options);
}


export function setDevelopPinned(client: ApiClient, pinned: boolean, options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetDevelopPinned', [pinned], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setDevelopPinned.method = 'Settings.SetDevelopPinned' as const;

export function subscribeSetDevelopPinned(client: ApiClient, pinned: boolean, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetDevelopPinned', [pinned], callback, onError, options);
}


export function setEditGroupOpen(client: ApiClient, id: string, open: boolean, options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetEditGroupOpen', [id, open], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setEditGroupOpen.method = 'Settings.SetEditGroupOpen' as const;

export function subscribeSetEditGroupOpen(client: ApiClient, id: string, open: boolean, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetEditGroupOpen', [id, open], callback, onError, options);
}


export function setExportDir(client: ApiClient, dir: string, options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetExportDir', [dir], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setExportDir.method = 'Settings.SetExportDir' as const;

export function subscribeSetExportDir(client: ApiClient, dir: string, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetExportDir', [dir], callback, onError, options);
}


export function setExportOptions(client: ApiClient, opts: ExportOptions, options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetExportOptions', [opts], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setExportOptions.method = 'Settings.SetExportOptions' as const;

export function subscribeSetExportOptions(client: ApiClient, opts: ExportOptions, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetExportOptions', [opts], callback, onError, options);
}


export function setGapMinutes(client: ApiClient, minutes: number, options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetGapMinutes', [minutes], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setGapMinutes.method = 'Settings.SetGapMinutes' as const;

export function subscribeSetGapMinutes(client: ApiClient, minutes: number, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetGapMinutes', [minutes], callback, onError, options);
}


export function setGroupAlias(client: ApiClient, parentPath: string, alias: string, options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetGroupAlias', [parentPath, alias], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setGroupAlias.method = 'Settings.SetGroupAlias' as const;

export function subscribeSetGroupAlias(client: ApiClient, parentPath: string, alias: string, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetGroupAlias', [parentPath, alias], callback, onError, options);
}


export function setPrerenderFullres(client: ApiClient, enabled: boolean, options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetPrerenderFullres', [enabled], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setPrerenderFullres.method = 'Settings.SetPrerenderFullres' as const;

export function subscribeSetPrerenderFullres(client: ApiClient, enabled: boolean, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetPrerenderFullres', [enabled], callback, onError, options);
}


export function setQuickDials(client: ApiClient, dials: string[], options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetQuickDials', [dials], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setQuickDials.method = 'Settings.SetQuickDials' as const;

export function subscribeSetQuickDials(client: ApiClient, dials: string[], callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetQuickDials', [dials], callback, onError, options);
}


export function setRailGroupOpen(client: ApiClient, parentPath: string, open: boolean, options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetRailGroupOpen', [parentPath, open], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setRailGroupOpen.method = 'Settings.SetRailGroupOpen' as const;

export function subscribeSetRailGroupOpen(client: ApiClient, parentPath: string, open: boolean, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetRailGroupOpen', [parentPath, open], callback, onError, options);
}


export function setRailWidth(client: ApiClient, px: number, options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetRailWidth', [px], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setRailWidth.method = 'Settings.SetRailWidth' as const;

export function subscribeSetRailWidth(client: ApiClient, px: number, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetRailWidth', [px], callback, onError, options);
}


export function setTheme(client: ApiClient, theme: ThemeType, options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetTheme', [theme], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setTheme.method = 'Settings.SetTheme' as const;

export function subscribeSetTheme(client: ApiClient, theme: ThemeType, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetTheme', [theme], callback, onError, options);
}


export function setThumbFit(client: ApiClient, fit: ThumbFitType, options?: RequestOptions): Promise<void> {
    return client.request<void>('Settings.SetThumbFit', [fit], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setThumbFit.method = 'Settings.SetThumbFit' as const;

export function subscribeSetThumbFit(client: ApiClient, fit: ThumbFitType, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Settings.SetThumbFit', [fit], callback, onError, options);
}

// React Hooks for Settings

/**
 * Subscribes to `Settings.GetUISettings` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useGetUISettings(options?: UseQueryOptions<UISettings>): UseQueryResult<UISettings> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => getUISettings(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'Settings.GetUISettings', params: [] } });
}

/**
 * Subscribes to `Settings.SetAutoPresets` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetAutoPresets(presets: AutoPreset[], options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, presets: AutoPreset[]) => setAutoPresets(client, presets, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [presets], _subscribe: { method: 'Settings.SetAutoPresets', params: [presets] } });
}

/**
 * Subscribes to `Settings.SetCullDials` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetCullDials(dials: string[], options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, dials: string[]) => setCullDials(client, dials, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [dials], _subscribe: { method: 'Settings.SetCullDials', params: [dials] } });
}

/**
 * Subscribes to `Settings.SetDevelopPinned` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetDevelopPinned(pinned: boolean, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, pinned: boolean) => setDevelopPinned(client, pinned, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [pinned], _subscribe: { method: 'Settings.SetDevelopPinned', params: [pinned] } });
}

/**
 * Subscribes to `Settings.SetEditGroupOpen` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetEditGroupOpen(id: string, open: boolean, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string, open: boolean) => setEditGroupOpen(client, id, open, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id, open], _subscribe: { method: 'Settings.SetEditGroupOpen', params: [id, open] } });
}

/**
 * Subscribes to `Settings.SetExportDir` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetExportDir(dir: string, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, dir: string) => setExportDir(client, dir, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [dir], _subscribe: { method: 'Settings.SetExportDir', params: [dir] } });
}

/**
 * Subscribes to `Settings.SetExportOptions` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetExportOptions(opts: ExportOptions, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, opts: ExportOptions) => setExportOptions(client, opts, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [opts], _subscribe: { method: 'Settings.SetExportOptions', params: [opts] } });
}

/**
 * Subscribes to `Settings.SetGapMinutes` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetGapMinutes(minutes: number, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, minutes: number) => setGapMinutes(client, minutes, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [minutes], _subscribe: { method: 'Settings.SetGapMinutes', params: [minutes] } });
}

/**
 * Subscribes to `Settings.SetGroupAlias` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetGroupAlias(parentPath: string, alias: string, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, parentPath: string, alias: string) => setGroupAlias(client, parentPath, alias, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [parentPath, alias], _subscribe: { method: 'Settings.SetGroupAlias', params: [parentPath, alias] } });
}

/**
 * Subscribes to `Settings.SetPrerenderFullres` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetPrerenderFullres(enabled: boolean, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, enabled: boolean) => setPrerenderFullres(client, enabled, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [enabled], _subscribe: { method: 'Settings.SetPrerenderFullres', params: [enabled] } });
}

/**
 * Subscribes to `Settings.SetQuickDials` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetQuickDials(dials: string[], options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, dials: string[]) => setQuickDials(client, dials, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [dials], _subscribe: { method: 'Settings.SetQuickDials', params: [dials] } });
}

/**
 * Subscribes to `Settings.SetRailGroupOpen` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetRailGroupOpen(parentPath: string, open: boolean, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, parentPath: string, open: boolean) => setRailGroupOpen(client, parentPath, open, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [parentPath, open], _subscribe: { method: 'Settings.SetRailGroupOpen', params: [parentPath, open] } });
}

/**
 * Subscribes to `Settings.SetRailWidth` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetRailWidth(px: number, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, px: number) => setRailWidth(client, px, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [px], _subscribe: { method: 'Settings.SetRailWidth', params: [px] } });
}

/**
 * Subscribes to `Settings.SetTheme` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetTheme(theme: ThemeType, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, theme: ThemeType) => setTheme(client, theme, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [theme], _subscribe: { method: 'Settings.SetTheme', params: [theme] } });
}

/**
 * Subscribes to `Settings.SetThumbFit` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetThumbFit(fit: ThumbFitType, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, fit: ThumbFitType) => setThumbFit(client, fit, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [fit], _subscribe: { method: 'Settings.SetThumbFit', params: [fit] } });
}
