// Code generated by aprot. DO NOT EDIT.
// Handler: Share
import { useCallback } from 'react';
import { ApiClient, useQuery } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
} from './client';

export interface GuestCaps {
    cull: boolean;
    edits: boolean;
    downloads: boolean;
}

export interface GuestSession {
    name: string;
    folderId: number;
    caps: GuestCaps;
}

export interface ShareLink {
    id: string;
    name: string;
    path: string;
    folderId: number;
    caps: GuestCaps;
    expiresAt: number;
    createdAt: number;
    lastSeen: number;
    expired: boolean;
    photoCount: number;
    url: string;
}

export interface ShareStatus {
    available: boolean;
    running: boolean;
    hostname: string;
    err: string;
    linkCount: number;
}


export function createLink(client: ApiClient, path: string, caps: GuestCaps, expiresInDays: number, options?: RequestOptions): Promise<ShareLink> {
    return client.request<ShareLink>('Share.CreateLink', [path, caps, expiresInDays], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
createLink.method = 'Share.CreateLink' as const;

export function subscribeCreateLink(client: ApiClient, path: string, caps: GuestCaps, expiresInDays: number, callback: (data: ShareLink) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<ShareLink>('Share.CreateLink', [path, caps, expiresInDays], callback, onError, options);
}


export function listLinks(client: ApiClient, options?: RequestOptions): Promise<ShareLink[]> {
    return client.request<ShareLink[]>('Share.ListLinks', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
listLinks.method = 'Share.ListLinks' as const;

export function subscribeListLinks(client: ApiClient, callback: (data: ShareLink[]) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<ShareLink[]>('Share.ListLinks', [], callback, onError, options);
}


export function revokeLink(client: ApiClient, id: string, options?: RequestOptions): Promise<void> {
    return client.request<void>('Share.RevokeLink', [id], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
revokeLink.method = 'Share.RevokeLink' as const;

export function subscribeRevokeLink(client: ApiClient, id: string, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('Share.RevokeLink', [id], callback, onError, options);
}


export function session(client: ApiClient, options?: RequestOptions): Promise<GuestSession> {
    return client.request<GuestSession>('Share.Session', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
session.method = 'Share.Session' as const;

export function subscribeSession(client: ApiClient, callback: (data: GuestSession) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<GuestSession>('Share.Session', [], callback, onError, options);
}


export function status(client: ApiClient, options?: RequestOptions): Promise<ShareStatus> {
    return client.request<ShareStatus>('Share.Status', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
status.method = 'Share.Status' as const;

export function subscribeStatus(client: ApiClient, callback: (data: ShareStatus) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<ShareStatus>('Share.Status', [], callback, onError, options);
}

// React Hooks for Share

/**
 * Subscribes to `Share.CreateLink` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useCreateLink(path: string, caps: GuestCaps, expiresInDays: number, options?: UseQueryOptions<ShareLink>): UseQueryResult<ShareLink> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, path: string, caps: GuestCaps, expiresInDays: number) => createLink(client, path, caps, expiresInDays, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [path, caps, expiresInDays], _subscribe: { method: 'Share.CreateLink', params: [path, caps, expiresInDays] } });
}

/**
 * Subscribes to `Share.ListLinks` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useListLinks(options?: UseQueryOptions<ShareLink[]>): UseQueryResult<ShareLink[]> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => listLinks(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'Share.ListLinks', params: [] } });
}

/**
 * Subscribes to `Share.RevokeLink` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useRevokeLink(id: string, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => revokeLink(client, id, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id], _subscribe: { method: 'Share.RevokeLink', params: [id] } });
}

/**
 * Subscribes to `Share.Session` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSession(options?: UseQueryOptions<GuestSession>): UseQueryResult<GuestSession> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => session(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'Share.Session', params: [] } });
}

/**
 * Subscribes to `Share.Status` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useStatus(options?: UseQueryOptions<ShareStatus>): UseQueryResult<ShareStatus> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => status(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'Share.Status', params: [] } });
}
