// Code generated by aprot. DO NOT EDIT.
// Handler: System
import { useCallback } from 'react';
import { ApiClient, useQuery } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
} from './client';

export interface CacheInfo {
    dir: string;
    bytes: number;
    files: number;
    isCustom: boolean;
}


export function clearCache(client: ApiClient, options?: RequestOptions): Promise<CacheInfo> {
    return client.request<CacheInfo>('System.ClearCache', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
clearCache.method = 'System.ClearCache' as const;

export function subscribeClearCache(client: ApiClient, callback: (data: CacheInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<CacheInfo>('System.ClearCache', [], callback, onError, options);
}


export function getCacheInfo(client: ApiClient, options?: RequestOptions): Promise<CacheInfo> {
    return client.request<CacheInfo>('System.GetCacheInfo', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
getCacheInfo.method = 'System.GetCacheInfo' as const;

export function subscribeGetCacheInfo(client: ApiClient, callback: (data: CacheInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<CacheInfo>('System.GetCacheInfo', [], callback, onError, options);
}


export function setCacheDir(client: ApiClient, path: string, options?: RequestOptions): Promise<CacheInfo> {
    return client.request<CacheInfo>('System.SetCacheDir', [path], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setCacheDir.method = 'System.SetCacheDir' as const;

export function subscribeSetCacheDir(client: ApiClient, path: string, callback: (data: CacheInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<CacheInfo>('System.SetCacheDir', [path], callback, onError, options);
}

// React Hooks for System

/**
 * Subscribes to `System.ClearCache` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useClearCache(options?: UseQueryOptions<CacheInfo>): UseQueryResult<CacheInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => clearCache(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'System.ClearCache', params: [] } });
}

/**
 * Subscribes to `System.GetCacheInfo` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useGetCacheInfo(options?: UseQueryOptions<CacheInfo>): UseQueryResult<CacheInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => getCacheInfo(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'System.GetCacheInfo', params: [] } });
}

/**
 * Subscribes to `System.SetCacheDir` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetCacheDir(path: string, options?: UseQueryOptions<CacheInfo>): UseQueryResult<CacheInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, path: string) => setCacheDir(client, path, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [path], _subscribe: { method: 'System.SetCacheDir', params: [path] } });
}
