// Code generated by aprot. DO NOT EDIT.
// Handler: System
import { useCallback } from 'react';
import { ApiClient, useQuery } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
} from './client';

export interface CacheInfo {
    dir: string;
    bytes: number;
    files: number;
    isCustom: boolean;
    capBytes: number;
}

export interface ModelFile {
    fileName: string;
    name?: string;
    purpose?: string;
    bytes: number;
}

export interface ModelsInfo {
    dir: string;
    models: ModelFile[];
}

export interface PairingRequest {
    id: string;
    code: string;
    name: string;
    platform: string;
    addr: string;
    expiresAt: number;
}

export interface RemoteAccessInfo {
    pairingToken: string;
    listenAddr: string;
    loopbackOnly: boolean;
    deviceName: string;
    pairingOpen: boolean;
}

export interface RemoteDeviceInfo {
    id: string;
    name: string;
    addr: string;
    addedAt: number;
    lastSeen: number;
}


export function clearCache(client: ApiClient, options?: RequestOptions): Promise<CacheInfo> {
    return client.request<CacheInfo>('System.ClearCache', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
clearCache.method = 'System.ClearCache' as const;

export function subscribeClearCache(client: ApiClient, callback: (data: CacheInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<CacheInfo>('System.ClearCache', [], callback, onError, options);
}


export function deleteModel(client: ApiClient, fileName: string, options?: RequestOptions): Promise<ModelsInfo> {
    return client.request<ModelsInfo>('System.DeleteModel', [fileName], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
deleteModel.method = 'System.DeleteModel' as const;

export function subscribeDeleteModel(client: ApiClient, fileName: string, callback: (data: ModelsInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<ModelsInfo>('System.DeleteModel', [fileName], callback, onError, options);
}


export function getCacheInfo(client: ApiClient, options?: RequestOptions): Promise<CacheInfo> {
    return client.request<CacheInfo>('System.GetCacheInfo', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
getCacheInfo.method = 'System.GetCacheInfo' as const;

export function subscribeGetCacheInfo(client: ApiClient, callback: (data: CacheInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<CacheInfo>('System.GetCacheInfo', [], callback, onError, options);
}


export function getModelsInfo(client: ApiClient, options?: RequestOptions): Promise<ModelsInfo> {
    return client.request<ModelsInfo>('System.GetModelsInfo', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
getModelsInfo.method = 'System.GetModelsInfo' as const;

export function subscribeGetModelsInfo(client: ApiClient, callback: (data: ModelsInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<ModelsInfo>('System.GetModelsInfo', [], callback, onError, options);
}


export function getRemoteAccess(client: ApiClient, options?: RequestOptions): Promise<RemoteAccessInfo> {
    return client.request<RemoteAccessInfo>('System.GetRemoteAccess', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
getRemoteAccess.method = 'System.GetRemoteAccess' as const;

export function subscribeGetRemoteAccess(client: ApiClient, callback: (data: RemoteAccessInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<RemoteAccessInfo>('System.GetRemoteAccess', [], callback, onError, options);
}


export function listPairingRequests(client: ApiClient, options?: RequestOptions): Promise<PairingRequest[]> {
    return client.request<PairingRequest[]>('System.ListPairingRequests', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
listPairingRequests.method = 'System.ListPairingRequests' as const;

export function subscribeListPairingRequests(client: ApiClient, callback: (data: PairingRequest[]) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<PairingRequest[]>('System.ListPairingRequests', [], callback, onError, options);
}


export function listRemoteDevices(client: ApiClient, options?: RequestOptions): Promise<RemoteDeviceInfo[]> {
    return client.request<RemoteDeviceInfo[]>('System.ListRemoteDevices', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
listRemoteDevices.method = 'System.ListRemoteDevices' as const;

export function subscribeListRemoteDevices(client: ApiClient, callback: (data: RemoteDeviceInfo[]) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<RemoteDeviceInfo[]>('System.ListRemoteDevices', [], callback, onError, options);
}


export function regeneratePairingToken(client: ApiClient, options?: RequestOptions): Promise<RemoteAccessInfo> {
    return client.request<RemoteAccessInfo>('System.RegeneratePairingToken', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
regeneratePairingToken.method = 'System.RegeneratePairingToken' as const;

export function subscribeRegeneratePairingToken(client: ApiClient, callback: (data: RemoteAccessInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<RemoteAccessInfo>('System.RegeneratePairingToken', [], callback, onError, options);
}


export function resolvePairing(client: ApiClient, id: string, approve: boolean, options?: RequestOptions): Promise<void> {
    return client.request<void>('System.ResolvePairing', [id, approve], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
resolvePairing.method = 'System.ResolvePairing' as const;

export function subscribeResolvePairing(client: ApiClient, id: string, approve: boolean, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('System.ResolvePairing', [id, approve], callback, onError, options);
}


export function revokeRemoteDevice(client: ApiClient, id: string, options?: RequestOptions): Promise<void> {
    return client.request<void>('System.RevokeRemoteDevice', [id], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
revokeRemoteDevice.method = 'System.RevokeRemoteDevice' as const;

export function subscribeRevokeRemoteDevice(client: ApiClient, id: string, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('System.RevokeRemoteDevice', [id], callback, onError, options);
}


export function setCacheCap(client: ApiClient, gb: number, options?: RequestOptions): Promise<CacheInfo> {
    return client.request<CacheInfo>('System.SetCacheCap', [gb], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setCacheCap.method = 'System.SetCacheCap' as const;

export function subscribeSetCacheCap(client: ApiClient, gb: number, callback: (data: CacheInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<CacheInfo>('System.SetCacheCap', [gb], callback, onError, options);
}


export function setCacheDir(client: ApiClient, path: string, options?: RequestOptions): Promise<CacheInfo> {
    return client.request<CacheInfo>('System.SetCacheDir', [path], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setCacheDir.method = 'System.SetCacheDir' as const;

export function subscribeSetCacheDir(client: ApiClient, path: string, callback: (data: CacheInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<CacheInfo>('System.SetCacheDir', [path], callback, onError, options);
}


export function setDeviceName(client: ApiClient, name: string, options?: RequestOptions): Promise<RemoteAccessInfo> {
    return client.request<RemoteAccessInfo>('System.SetDeviceName', [name], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setDeviceName.method = 'System.SetDeviceName' as const;

export function subscribeSetDeviceName(client: ApiClient, name: string, callback: (data: RemoteAccessInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<RemoteAccessInfo>('System.SetDeviceName', [name], callback, onError, options);
}


export function setPairingOpen(client: ApiClient, open: boolean, options?: RequestOptions): Promise<RemoteAccessInfo> {
    return client.request<RemoteAccessInfo>('System.SetPairingOpen', [open], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
setPairingOpen.method = 'System.SetPairingOpen' as const;

export function subscribeSetPairingOpen(client: ApiClient, open: boolean, callback: (data: RemoteAccessInfo) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<RemoteAccessInfo>('System.SetPairingOpen', [open], callback, onError, options);
}

// React Hooks for System

/**
 * Subscribes to `System.ClearCache` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useClearCache(options?: UseQueryOptions<CacheInfo>): UseQueryResult<CacheInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => clearCache(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'System.ClearCache', params: [] } });
}

/**
 * Subscribes to `System.DeleteModel` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useDeleteModel(fileName: string, options?: UseQueryOptions<ModelsInfo>): UseQueryResult<ModelsInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, fileName: string) => deleteModel(client, fileName, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [fileName], _subscribe: { method: 'System.DeleteModel', params: [fileName] } });
}

/**
 * Subscribes to `System.GetCacheInfo` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useGetCacheInfo(options?: UseQueryOptions<CacheInfo>): UseQueryResult<CacheInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => getCacheInfo(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'System.GetCacheInfo', params: [] } });
}

/**
 * Subscribes to `System.GetModelsInfo` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useGetModelsInfo(options?: UseQueryOptions<ModelsInfo>): UseQueryResult<ModelsInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => getModelsInfo(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'System.GetModelsInfo', params: [] } });
}

/**
 * Subscribes to `System.GetRemoteAccess` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useGetRemoteAccess(options?: UseQueryOptions<RemoteAccessInfo>): UseQueryResult<RemoteAccessInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => getRemoteAccess(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'System.GetRemoteAccess', params: [] } });
}

/**
 * Subscribes to `System.ListPairingRequests` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useListPairingRequests(options?: UseQueryOptions<PairingRequest[]>): UseQueryResult<PairingRequest[]> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => listPairingRequests(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'System.ListPairingRequests', params: [] } });
}

/**
 * Subscribes to `System.ListRemoteDevices` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useListRemoteDevices(options?: UseQueryOptions<RemoteDeviceInfo[]>): UseQueryResult<RemoteDeviceInfo[]> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => listRemoteDevices(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'System.ListRemoteDevices', params: [] } });
}

/**
 * Subscribes to `System.RegeneratePairingToken` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useRegeneratePairingToken(options?: UseQueryOptions<RemoteAccessInfo>): UseQueryResult<RemoteAccessInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => regeneratePairingToken(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'System.RegeneratePairingToken', params: [] } });
}

/**
 * Subscribes to `System.ResolvePairing` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useResolvePairing(id: string, approve: boolean, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string, approve: boolean) => resolvePairing(client, id, approve, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id, approve], _subscribe: { method: 'System.ResolvePairing', params: [id, approve] } });
}

/**
 * Subscribes to `System.RevokeRemoteDevice` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useRevokeRemoteDevice(id: string, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, id: string) => revokeRemoteDevice(client, id, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [id], _subscribe: { method: 'System.RevokeRemoteDevice', params: [id] } });
}

/**
 * Subscribes to `System.SetCacheCap` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetCacheCap(gb: number, options?: UseQueryOptions<CacheInfo>): UseQueryResult<CacheInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, gb: number) => setCacheCap(client, gb, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [gb], _subscribe: { method: 'System.SetCacheCap', params: [gb] } });
}

/**
 * Subscribes to `System.SetCacheDir` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetCacheDir(path: string, options?: UseQueryOptions<CacheInfo>): UseQueryResult<CacheInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, path: string) => setCacheDir(client, path, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [path], _subscribe: { method: 'System.SetCacheDir', params: [path] } });
}

/**
 * Subscribes to `System.SetDeviceName` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetDeviceName(name: string, options?: UseQueryOptions<RemoteAccessInfo>): UseQueryResult<RemoteAccessInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, name: string) => setDeviceName(client, name, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [name], _subscribe: { method: 'System.SetDeviceName', params: [name] } });
}

/**
 * Subscribes to `System.SetPairingOpen` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useSetPairingOpen(open: boolean, options?: UseQueryOptions<RemoteAccessInfo>): UseQueryResult<RemoteAccessInfo> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, open: boolean) => setPairingOpen(client, open, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [open], _subscribe: { method: 'System.SetPairingOpen', params: [open] } });
}
