// Code generated by aprot. DO NOT EDIT.

import { useState, useEffect, useCallback, useSyncExternalStore } from 'react';
import type { ApiClient, RequestOptions } from './client';
import { useApiClient } from './client';
import type { SharedTaskState, TaskStateEvent, TaskUpdateEvent, TaskNode, RequestTaskTreeEvent, RequestTaskOutputEvent } from './tasks-handler';

export interface TaskRequestOptions extends RequestOptions {
    onTaskProgress?: (tasks: TaskNode[]) => void;
    onOutput?: (output: string, taskId?: string) => void;
}

export function taskOptions(client: ApiClient, opts: TaskRequestOptions): RequestOptions {
    const { onTaskProgress, onOutput, ...base } = opts;
    if (!onTaskProgress && !onOutput) return opts;

    const unsubs: (() => void)[] = [];
    let requestId: string | null = null;

    if (onTaskProgress) {
        unsubs.push(client.onPush<RequestTaskTreeEvent>('RequestTaskTreeEvent', (e) => {
            if (e.requestId === requestId) onTaskProgress(e.tasks);
        }));
    }
    if (onOutput) {
        unsubs.push(client.onPush<RequestTaskOutputEvent>('RequestTaskOutputEvent', (e) => {
            if (e.requestId === requestId) onOutput(e.output, e.taskId);
        }));
    }

    return {
        ...base,
        _onStart: (id: string) => { requestId = id; },
        _onSettle: () => { unsubs.forEach(fn => fn()); },
    };
}

export function cancelSharedTask(client: ApiClient, taskId: string): Promise<void> {
    return client.request<void>('tasksHandler.CancelTask', [taskId]);
}


// Shared task hooks

function patchTaskNodes(nodes: TaskNode[], event: TaskUpdateEvent): TaskNode[] {
    return nodes.map((n) => {
        if (n.id === event.taskId) {
            return { ...n, current: event.current ?? n.current, total: event.total ?? n.total };
        }
        return n.children ? { ...n, children: patchTaskNodes(n.children, event) } : n;
    });
}

// Shared-task state lives in one store per client, NOT in per-hook state:
// full TaskStateEvent broadcasts fire only on lifecycle changes, so a hook
// instance mounting mid-task would start empty and stay empty until the next
// lifecycle event. The store attaches once and is never torn down.
interface SharedTaskStore {
    subscribe: (listener: () => void) => () => void;
    getSnapshot: () => SharedTaskState[];
}

const taskStores = new WeakMap<ApiClient, SharedTaskStore>();

function sharedTaskStore(client: ApiClient): SharedTaskStore {
    let store = taskStores.get(client);
    if (store) return store;

    const listeners = new Set<() => void>();
    let tasks: SharedTaskState[] = [];
    // Bumped on every full snapshot so an in-flight ListTasks seed can never
    // clobber a fresher TaskStateEvent.
    let snapshotEpoch = 0;

    const set = (next: SharedTaskState[]) => {
        tasks = next;
        listeners.forEach((fn) => fn());
    };

    client.onPush<TaskStateEvent>('TaskStateEvent', (event) => {
        snapshotEpoch++;
        set(event.tasks);
    });
    // Progress ticks travel as TaskUpdateEvent between full snapshots —
    // full TaskStateEvent broadcasts only mark lifecycle changes. Fold
    // them in so consumers see live current/total.
    client.onPush<TaskUpdateEvent>('TaskUpdateEvent', (event) => {
        if (event.current == null && event.total == null) return;
        set(tasks.map((t) => {
            if (t.id === event.taskId) {
                return { ...t, current: event.current ?? t.current, total: event.total ?? t.total };
            }
            return t.children ? { ...t, children: patchTaskNodes(t.children, event) } : t;
        }));
    });

    // Hydrate from the server snapshot now and on every (re)connect — events
    // missed while mounting late or disconnected (a task finishing, say)
    // would otherwise leave stale or empty state.
    const seed = () => {
        const epoch = snapshotEpoch;
        client.request<SharedTaskState[]>('tasksHandler.ListTasks', []).then((snapshot) => {
            if (snapshotEpoch !== epoch) return;
            snapshotEpoch++;
            set(snapshot ?? []);
        }).catch(() => {});
    };
    if (client.isConnected()) seed();
    client.onStateChange((state) => { if (state === 'connected') seed(); });

    store = {
        subscribe: (listener) => { listeners.add(listener); return () => { listeners.delete(listener); }; },
        getSnapshot: () => tasks,
    };
    taskStores.set(client, store);
    return store;
}

export function useSharedTasks(): SharedTaskState[] {
    const client = useApiClient();
    const store = sharedTaskStore(client);
    return useSyncExternalStore(store.subscribe, store.getSnapshot);
}

export function useSharedTask(id: string): SharedTaskState | null {
    const tasks = useSharedTasks();
    return tasks.find(t => t.id === id) ?? null;
}

export function useMyTasks(): SharedTaskState[] {
    const tasks = useSharedTasks();
    return tasks.filter(t => t.isOwner && !t.parentId);
}

export function useTaskOutput(taskId: string): { lines: string[]; clear: () => void } {
    const client = useApiClient();
    const [lines, setLines] = useState<string[]>([]);

    useEffect(() => {
        return client.onPush<TaskUpdateEvent>('TaskUpdateEvent', (event) => {
            if (event.taskId === taskId && event.output != null) {
                setLines((prev) => [...prev, event.output!]);
            }
        });
    }, [client, taskId]);

    const clear = useCallback(() => setLines([]), []);

    return { lines, clear };
}


export interface TaskMeta {
    kind: string;
    folder?: string;
    folderPath?: string;
    destDir?: string;
}
