// Code generated by aprot. DO NOT EDIT.
// Handler: tasksHandler
import { useCallback } from 'react';
import { ApiClient, useQuery, usePushEvent } from './client';
import type {
    RequestOptions,
    UseQueryOptions,
    UseQueryResult,
    PushHandler,
    UsePushResult,
} from './client';

export const TaskNodeStatus = {
    Created: "created",
    Running: "running",
    Completed: "completed",
    Failed: "failed",
} as const;
export type TaskNodeStatusType = typeof TaskNodeStatus[keyof typeof TaskNodeStatus];

export interface RequestTaskOutputEvent {
    requestId: string;
    taskId: string;
    output: string;
}

export interface RequestTaskProgressEvent {
    requestId: string;
    taskId: string;
    current: number;
    total: number;
}

export interface RequestTaskTreeEvent {
    requestId: string;
    tasks: TaskNode[];
}

export interface SharedTaskState {
    id: string;
    parentId?: string;
    title: string;
    status: TaskNodeStatusType;
    error?: string;
    current?: number;
    total?: number;
    meta?: unknown;
    children?: TaskNode[];
    isOwner: boolean;
}

export interface TaskNode {
    id: string;
    title: string;
    status: TaskNodeStatusType;
    error?: string;
    current?: number;
    total?: number;
    meta?: unknown;
    children?: TaskNode[];
}

export interface TaskStateEvent {
    tasks: SharedTaskState[];
}

export interface TaskUpdateEvent {
    taskId: string;
    output?: string;
    current?: number;
    total?: number;
}


export function cancelTask(client: ApiClient, taskId: string, options?: RequestOptions): Promise<void> {
    return client.request<void>('tasksHandler.CancelTask', [taskId], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
cancelTask.method = 'tasksHandler.CancelTask' as const;

export function subscribeCancelTask(client: ApiClient, taskId: string, callback: (data: void) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<void>('tasksHandler.CancelTask', [taskId], callback, onError, options);
}


export function listTasks(client: ApiClient, options?: RequestOptions): Promise<SharedTaskState[]> {
    return client.request<SharedTaskState[]>('tasksHandler.ListTasks', [], options);
}
// Wire-method tag consumed by useQuerySuspense to key the promise cache and
// open the matching server subscription. Stable identifier across builds
// (unaffected by minification, unlike Function.name).
listTasks.method = 'tasksHandler.ListTasks' as const;

export function subscribeListTasks(client: ApiClient, callback: (data: SharedTaskState[]) => void, onError?: (error: Error) => void, options?: { onPatch?: (patch: unknown) => void }): () => void {
    return client.subscribe<SharedTaskState[]>('tasksHandler.ListTasks', [], callback, onError, options);
}

export function onTaskStateEvent(client: ApiClient, handler: PushHandler<TaskStateEvent>): () => void {
    return client.onPush<TaskStateEvent>('TaskStateEvent', handler);
}

export function onTaskUpdateEvent(client: ApiClient, handler: PushHandler<TaskUpdateEvent>): () => void {
    return client.onPush<TaskUpdateEvent>('TaskUpdateEvent', handler);
}

export function onRequestTaskTreeEvent(client: ApiClient, handler: PushHandler<RequestTaskTreeEvent>): () => void {
    return client.onPush<RequestTaskTreeEvent>('RequestTaskTreeEvent', handler);
}

export function onRequestTaskOutputEvent(client: ApiClient, handler: PushHandler<RequestTaskOutputEvent>): () => void {
    return client.onPush<RequestTaskOutputEvent>('RequestTaskOutputEvent', handler);
}

export function onRequestTaskProgressEvent(client: ApiClient, handler: PushHandler<RequestTaskProgressEvent>): () => void {
    return client.onPush<RequestTaskProgressEvent>('RequestTaskProgressEvent', handler);
}

// React Hooks for tasksHandler

/**
 * Subscribes to `tasksHandler.CancelTask` with the given parameters and re-renders
 * automatically when the server triggers a refresh. When the parameters
 * change, the previous subscription is canceled and a new one starts.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useCancelTask(taskId: string, options?: UseQueryOptions<void>): UseQueryResult<void> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal, taskId: string) => cancelTask(client, taskId, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, params: [taskId], _subscribe: { method: 'tasksHandler.CancelTask', params: [taskId] } });
}

/**
 * Subscribes to `tasksHandler.ListTasks` and re-renders automatically when the
 * server triggers a refresh. The subscription is cleaned up on unmount.
 * See {@link UseQueryResult} for return value details — including the
 * query-scoped `mutate(action)` helper for refetch-after-mutation flows.
 */
export function useListTasks(options?: UseQueryOptions<SharedTaskState[]>): UseQueryResult<SharedTaskState[]> {
    const wrappedFn = useCallback(
        (client: ApiClient, signal: AbortSignal) => listTasks(client, { signal }),
        [],
    );
    return useQuery(wrappedFn, { ...options, _subscribe: { method: 'tasksHandler.ListTasks', params: [] } });
}

export function useTaskStateEvent(options?: { maxEvents?: number }): UsePushResult<TaskStateEvent> {
    return usePushEvent(onTaskStateEvent, options);
}

export function useTaskUpdateEvent(options?: { maxEvents?: number }): UsePushResult<TaskUpdateEvent> {
    return usePushEvent(onTaskUpdateEvent, options);
}

export function useRequestTaskTreeEvent(options?: { maxEvents?: number }): UsePushResult<RequestTaskTreeEvent> {
    return usePushEvent(onRequestTaskTreeEvent, options);
}

export function useRequestTaskOutputEvent(options?: { maxEvents?: number }): UsePushResult<RequestTaskOutputEvent> {
    return usePushEvent(onRequestTaskOutputEvent, options);
}

export function useRequestTaskProgressEvent(options?: { maxEvents?: number }): UsePushResult<RequestTaskProgressEvent> {
    return usePushEvent(onRequestTaskProgressEvent, options);
}
