// Code generated by aprot. DO NOT EDIT.

import { useState, useEffect, useCallback } from 'react';
import type { ApiClient, RequestOptions } from './client';
import { useApiClient } from './client';
import type { SharedTaskState, TaskStateEvent, TaskUpdateEvent, TaskNode, RequestTaskTreeEvent, RequestTaskOutputEvent } from './tasks-handler';

export interface TaskRequestOptions extends RequestOptions {
    onTaskProgress?: (tasks: TaskNode[]) => void;
    onOutput?: (output: string, taskId?: string) => void;
}

export function taskOptions(client: ApiClient, opts: TaskRequestOptions): RequestOptions {
    const { onTaskProgress, onOutput, ...base } = opts;
    if (!onTaskProgress && !onOutput) return opts;

    const unsubs: (() => void)[] = [];
    let requestId: string | null = null;

    if (onTaskProgress) {
        unsubs.push(client.onPush<RequestTaskTreeEvent>('RequestTaskTreeEvent', (e) => {
            if (e.requestId === requestId) onTaskProgress(e.tasks);
        }));
    }
    if (onOutput) {
        unsubs.push(client.onPush<RequestTaskOutputEvent>('RequestTaskOutputEvent', (e) => {
            if (e.requestId === requestId) onOutput(e.output, e.taskId);
        }));
    }

    return {
        ...base,
        _onStart: (id: string) => { requestId = id; },
        _onSettle: () => { unsubs.forEach(fn => fn()); },
    };
}

export function cancelSharedTask(client: ApiClient, taskId: string): Promise<void> {
    return client.request<void>('tasksHandler.CancelTask', [taskId]);
}


// Shared task hooks

function patchTaskNodes(nodes: TaskNode[], event: TaskUpdateEvent): TaskNode[] {
    return nodes.map((n) => {
        if (n.id === event.taskId) {
            return { ...n, current: event.current ?? n.current, total: event.total ?? n.total };
        }
        return n.children ? { ...n, children: patchTaskNodes(n.children, event) } : n;
    });
}

export function useSharedTasks(): SharedTaskState[] {
    const client = useApiClient();
    const [tasks, setTasks] = useState<SharedTaskState[]>([]);

    useEffect(() => {
        const offState = client.onPush<TaskStateEvent>('TaskStateEvent', (event) => {
            setTasks(event.tasks);
        });
        // Progress ticks travel as TaskUpdateEvent between full snapshots —
        // full TaskStateEvent broadcasts only mark lifecycle changes. Fold
        // them in so consumers see live current/total.
        const offUpdate = client.onPush<TaskUpdateEvent>('TaskUpdateEvent', (event) => {
            if (event.current == null && event.total == null) return;
            setTasks((prev) => prev.map((t) => {
                if (t.id === event.taskId) {
                    return { ...t, current: event.current ?? t.current, total: event.total ?? t.total };
                }
                return t.children ? { ...t, children: patchTaskNodes(t.children, event) } : t;
            }));
        });
        return () => { offState(); offUpdate(); };
    }, [client]);

    return tasks;
}

export function useSharedTask(id: string): SharedTaskState | null {
    const tasks = useSharedTasks();
    return tasks.find(t => t.id === id) ?? null;
}

export function useMyTasks(): SharedTaskState[] {
    const tasks = useSharedTasks();
    return tasks.filter(t => t.isOwner && !t.parentId);
}

export function useTaskOutput(taskId: string): { lines: string[]; clear: () => void } {
    const client = useApiClient();
    const [lines, setLines] = useState<string[]>([]);

    useEffect(() => {
        return client.onPush<TaskUpdateEvent>('TaskUpdateEvent', (event) => {
            if (event.taskId === taskId && event.output != null) {
                setLines((prev) => [...prev, event.output!]);
            }
        });
    }, [client, taskId]);

    const clear = useCallback(() => setLines([]), []);

    return { lines, clear };
}


export interface TaskMeta {
    kind: string;
    folder?: string;
    destDir?: string;
}
