package pyramid

import (
	"image"
	"math"

	"github.com/marrasen/marraw/internal/edit"
)

// Tilt shift — depth-graded defocus, the one develop stage that reads the AI
// depth map without a mask around it.
//
// The shape of the problem is what makes it a stage of its own. A mask
// defocuses at ONE radius through its coverage, so an AI depth mask carrying
// MaskAdjust.Blur gives two zones and a feathered seam. Depth of field is a
// RAMP: the circle of confusion grows with the distance from the focal plane,
// which needs a per-pixel radius. Three decisions carry the result:
//
//   - The coc plane comes from the mask machinery, not from a second sampler.
//     ApplyTilt synthesizes the AI depth mask the effect describes and runs it
//     through newMaskEvaluator/weightPlaneFrom, so the depth window is
//     registered to the render by exactly the code an AI depth mask uses —
//     including the guided-filter edge refinement on high-resolution renders
//     (guided.go) and the derived-coverage LRU, which is why dragging the
//     window re-derives nothing. coc is then that plane inverted: 0 where the
//     photo stays sharp, 255 at full defocus.
//   - A per-pixel radius is approximated by tiltLevels DISCRETE blur levels
//     that the composite interpolates between, rather than by a variable-width
//     gather. A running-sum box blur costs the same at any radius but only at
//     a CONSTANT one; a per-pixel radius would force a per-pixel kernel walk,
//     which at the reaches this effect uses is orders of magnitude more work.
//     Three levels plus the sharp original is enough that the interpolation
//     reads as continuous.
//   - Each level gathers with weight min(coc/level, 1), so a pixel contributes
//     to a blur level only once it is at least that defocused itself. This is
//     the fxSource weight-normalized gather with the coc plane in the mask's
//     place, and it is what stops the sharp subject printing a ghost of itself
//     into the background behind it — the tell of every cheap fake bokeh.
//
// Levels are computed on the shared fxPlaneLongEdge working buffer in linear
// light (fxLin/fxEnc), so a 1024 draft, a 2048 settle, a 1:1 tile and a 60 MP
// export all compute the identical effect at identical cost.
//
// Known omission, deliberate for a first version: real foreground bokeh
// SCATTERS — an out-of-focus branch in front of the subject spills over it.
// This gathers, so the sharp subject keeps a crisp edge against a blurred
// foreground. Fixing that needs a scatter pass, not a tweak here.
const (
	// tiltBlurFrac is the defocus radius at TiltAmount = 1, as a fraction of
	// the working buffer's long edge — fxBlurFrac's contract and its value, so
	// the two blurs are the same strength at the same dial position.
	tiltBlurFrac = 0.06
	// tiltLevels is how many blur radii the ramp is quantized to (level k has
	// radius k/tiltLevels of the maximum); the composite lerps between the
	// bracketing pair, with the untouched render as the implicit level 0.
	tiltLevels = 3
	// tiltLevelRadius is the blur radius, in the level buffer's own pixels,
	// that tiltLevelDims sizes each level to reach. Wide enough that three
	// iterated box passes are a convincing disc and that the bilinear upsample
	// back to the render is well below the level's own softness; every pixel
	// past it is a pixel of detail the blur is about to throw away anyway.
	tiltLevelRadius = 12
	// tiltFalloff is the depth width the defocus ramps in over, fed to the
	// synthesized mask as its Feather. deriveCoverage's AIDepth case reads
	// Feather*0.25, so 1 ramps over a quarter of the photo's depth range on
	// each side of the window — wide enough to read as falloff rather than as
	// an edge, narrow enough that the far end still reaches full blur.
	tiltFalloff = 1.0
)

// ApplyTilt applies the depth-graded defocus in place, and returns the
// detail-suppression plane the caller must hand ApplyDetail (nil when nothing
// was defocused): clarity's large-radius unsharp mask would otherwise re-amplify
// the blurred background into a bright rim around the sharp subject, exactly as
// it would around a defocusing mask.
//
// Renders with no depth map for the stamped version are a silent no-op — the
// AI-mask contract, so a sidecar from another machine renders without the
// effect instead of failing.
func ApplyTilt(img *image.RGBA, e *edit.Params, ai AIMapSet) []uint8 {
	if !e.HasTilt() {
		return nil
	}
	b := img.Bounds()
	w, h := b.Dx(), b.Dy()
	if w < 4 || h < 4 {
		return nil
	}
	// newMaskEvaluator's AI arm, opened up for the edge clamp: a mask's
	// coverage may legitimately stop before the frame border, but a depth
	// field read across the whole photo may not (see brushEval.clampEdge).
	base := newAIEval(tiltMask(e), newMaskFrame(w, h, e), ai)
	if base == nil {
		return nil // map not generated (or generated by another model version)
	}
	base.clampEdge = true
	var ev maskEvaluator = base
	if g := newGuidedEval(base, img); g != nil {
		ev = g
	}

	// The evaluator draws what stays SHARP; invert in place to the circle of
	// confusion rather than allocating a second full-resolution plane, which
	// on a 60 MP export is 60 MB that buys nothing. An empty box needs no
	// special case: an all-zero focus plane inverts to an all-defocused frame,
	// which is what a window that excludes every depth means.
	coc, _ := weightPlaneFrom(ev, w, h)
	anyBlur := false
	for i, v := range coc {
		coc[i] = 255 - v
		if coc[i] != 0 {
			anyBlur = true
		}
	}
	if !anyBlur {
		return nil // the window covers the whole depth range: nothing defocuses
	}

	long := max(w, h)
	work := min(long, fxPlaneLongEdge)
	ww := max(4, w*work/long)
	wh := max(4, h*work/long)
	rMax := e.TiltAmount * tiltBlurFrac * float64(max(ww, wh))
	if rMax < 1 {
		// The dial is too low to reach a single working-buffer pixel: nothing
		// ran, so nothing may claim the render's sharpness either (applyMaskFX's
		// `destroyed` tracking, for the same reason).
		return nil
	}

	lin, wcoc := newTiltSource(img, coc, ww, wh)
	gather := tiltErode(wcoc, ww, wh)
	levels := make([]tiltLevelView, tiltLevels)
	for k := range levels {
		// Level k blurs at (k+1)/tiltLevels of the maximum radius, gathering
		// only pixels at least that defocused — and on a buffer sized to that
		// radius (tiltLevelDims), which is where most of the stage's cost went
		// before it was allowed to shrink.
		frac := float64(k+1) / tiltLevels
		lw, lh := tiltLevelDims(ww, wh, frac*rMax)
		src, g := lin, gather
		if lw != ww || lh != wh {
			src, g = tiltDownscale(lin, gather, ww, wh, lw, lh)
		}
		r := max(1, int(math.Round(frac*rMax*float64(max(lw, lh))/float64(max(ww, wh)))))
		levels[k] = newTiltLevelView(tiltLevel(src, g, lw, lh, frac, r), w, h)
	}
	tiltComposite(img, coc, levels)

	// coc is the suppression plane once scaled by the amount — reused in place
	// for the same reason it was inverted in place.
	k := int32(math.Round(e.TiltAmount * 255))
	for i, v := range coc {
		coc[i] = uint8(int32(v) * k / 255)
	}
	return coc
}

// tiltMask is the AI depth mask the effect's params describe: the window that
// stays sharp. Building a real mask rather than reaching into the map directly
// is what buys the whole registration chain — oriented-frame sampling through
// maskFrame, crop and straighten, the guided refinement, and the coverage LRU
// (whose key is the same one a hand-added depth mask uses, so the two share
// derived planes when their windows match).
func tiltMask(e *edit.Params) *edit.Mask {
	return &edit.Mask{
		Type:    edit.MaskAI,
		AIKind:  edit.AIDepth,
		MapVer:  e.TiltMapVer,
		DepthLo: e.TiltLo,
		DepthHi: e.TiltHi,
		Feather: tiltFalloff,
	}
}

// newTiltSource area-averages the render down to the working buffer,
// linearizing on the way, and brings the coc plane with it. Unlike newFXSource
// nothing is premultiplied here: each blur level needs its own weight, so the
// planes are shared plain and premultiplied per level.
func newTiltSource(img *image.RGBA, coc []uint8, ww, wh int) (*fxSource, []uint8) {
	b := img.Bounds()
	w, h := b.Dx(), b.Dy()
	n := ww * wh
	s := &fxSource{
		w: ww, h: wh,
		r: make([]uint16, n), g: make([]uint16, n), b: make([]uint16, n),
	}
	out := make([]uint8, n)
	// The interactive draft renders at or below fxPlaneLongEdge, so the working
	// buffer IS the render — skip the block machinery for a straight row walk
	// (newFXSource's fast path, for the same reason).
	if ww == w && wh == h {
		fxBands(wh, func(y0, y1 int) {
			for y := y0; y < y1; y++ {
				row := img.Pix[y*img.Stride : y*img.Stride+w*4]
				for x := range ww {
					j := y*ww + x
					i := x * 4
					s.r[j] = fxLin[row[i]]
					s.g[j] = fxLin[row[i+1]]
					s.b[j] = fxLin[row[i+2]]
				}
			}
			copy(out[y0*ww:y1*ww], coc[y0*w:y1*w])
		})
		return s, out
	}
	fxBands(wh, func(y0, y1 int) {
		for y := y0; y < y1; y++ {
			sy0 := y * h / wh
			sy1 := max(sy0+1, (y+1)*h/wh)
			for x := range ww {
				sx0 := x * w / ww
				sx1 := max(sx0+1, (x+1)*w/ww)
				var ar, ag, ab, ac, cnt int64
				for sy := sy0; sy < sy1; sy++ {
					row := img.Pix[sy*img.Stride:]
					crow := coc[sy*w:]
					for sx := sx0; sx < sx1; sx++ {
						i := sx * 4
						ar += int64(fxLin[row[i]])
						ag += int64(fxLin[row[i+1]])
						ab += int64(fxLin[row[i+2]])
						ac += int64(crow[sx])
						cnt++
					}
				}
				j := y*ww + x
				s.r[j] = uint16(ar / cnt)
				s.g[j] = uint16(ag / cnt)
				s.b[j] = uint16(ab / cnt)
				out[j] = uint8(ac / cnt)
			}
		}
	})
	return s, out
}

// tiltLevelDims sizes one blur level's own buffer. fxPlaneLongEdge's argument
// — a defocused region carries no detail finer than its blur radius, so
// computing it small and upsampling is invisible — applies per LEVEL, not just
// once for the stage: the widest level throws away far more detail than the
// narrowest and has no business costing the same. Each level is therefore
// computed at whatever resolution puts its radius on tiltLevelRadius pixels,
// capped at the shared working buffer (which a small dial stays at, since its
// radius is only a pixel or two there to begin with).
//
// The size depends on the effect's own reach and the frame's aspect, never on
// the render's resolution, so a draft, a settle, a tile and an export still
// compute the identical effect.
func tiltLevelDims(ww, wh int, r float64) (int, int) {
	long := max(ww, wh)
	if r <= tiltLevelRadius {
		return ww, wh
	}
	scaled := min(long, max(16, int(math.Round(float64(long)*tiltLevelRadius/r))))
	return max(4, ww*scaled/long), max(4, wh*scaled/long)
}

// tiltDownscale area-averages the linear working buffer and its gather coc to
// one level's smaller grid. The two travel together because a level's weights
// have to describe the very pixels it is about to average.
func tiltDownscale(lin *fxSource, coc []uint8, ww, wh, nw, nh int) (*fxSource, []uint8) {
	n := nw * nh
	out := &fxSource{
		w: nw, h: nh,
		r: make([]uint16, n), g: make([]uint16, n), b: make([]uint16, n),
	}
	oc := make([]uint8, n)
	fxBands(nh, func(y0, y1 int) {
		for y := y0; y < y1; y++ {
			sy0 := y * wh / nh
			sy1 := max(sy0+1, (y+1)*wh/nh)
			for x := range nw {
				sx0 := x * ww / nw
				sx1 := max(sx0+1, (x+1)*ww/nw)
				var ar, ag, ab, ac, cnt int64
				for sy := sy0; sy < sy1; sy++ {
					for sx := sx0; sx < sx1; sx++ {
						j := sy*ww + sx
						ar += int64(lin.r[j])
						ag += int64(lin.g[j])
						ab += int64(lin.b[j])
						ac += int64(coc[j])
						cnt++
					}
				}
				j := y*nw + x
				out.r[j] = uint16(ar / cnt)
				out.g[j] = uint16(ag / cnt)
				out.b[j] = uint16(ab / cnt)
				oc[j] = uint8(ac / cnt)
			}
		}
	})
	return out, oc
}

// tiltErode is the gather-side erosion, fxSource's idea in the form a
// continuous depth field needs: the coc a level GATHERS with is the local
// MINIMUM over tiltErodeRadius, while the coc the result is COMPOSITED with
// stays as the depth map drew it. A pixel therefore lends its colour to a
// defocus gather only if everything around it is at least that defocused too.
//
// That is what keeps a sharp subject out of the background behind it. The
// depth map resolves an object boundary over a few soft pixels while the
// photo resolves it exactly, so the sliver of pixels the map calls
// half-defocused still holds the SUBJECT's colour — and a plain weighted
// gather spreads it a whole blur radius into the background as a ghost.
//
// A local minimum rather than fxSource's blur-and-knee on purpose: the knee is
// tuned for a matte that is 0 or 255 nearly everywhere, and on a smooth depth
// ramp it would down-weight every pixel by how near-focus it is, biasing each
// gather toward its deeper neighbours — a directional smear across the whole
// gradient. A minimum leaves a smooth ramp alone (it shifts every weight by
// the same couple of pixels of gradient) and bites only at discontinuities,
// which is exactly where the ghost comes from.
func tiltErode(coc []uint8, ww, wh int) []uint8 {
	const r = 2
	tmp := make([]uint8, len(coc))
	out := make([]uint8, len(coc))
	fxBands(wh, func(y0, y1 int) {
		for y := y0; y < y1; y++ {
			row := coc[y*ww : (y+1)*ww]
			trow := tmp[y*ww : (y+1)*ww]
			for x := range ww {
				m := row[x]
				for k := max(0, x-r); k < min(ww, x+r+1); k++ {
					if row[k] < m {
						m = row[k]
					}
				}
				trow[x] = m
			}
		}
	})
	fxBands(wh, func(y0, y1 int) {
		for y := y0; y < y1; y++ {
			for x := range ww {
				m := tmp[y*ww+x]
				for k := max(0, y-r); k < min(wh, y+r+1); k++ {
					if v := tmp[k*ww+x]; v < m {
						m = v
					}
				}
				out[y*ww+x] = m
			}
		}
	})
	return out
}

// tiltLevel builds one blur level: the working buffer premultiplied by
// min(coc/frac, 1), box-blurred at radius r, and divided back through. The
// weight is the whole point — a pixel sharper than this level contributes
// nothing to it, so the in-focus subject cannot bleed into the defocused
// surround (fxSource's weight-normalized gather, with coc as the mask).
//
// After resolve, r/g/b hold plain linear light and a holds the accumulated
// weight; a == 0 marks a pixel no defocused neighbour reached, which the
// composite falls back from.
func tiltLevel(lin *fxSource, coc []uint8, ww, wh int, frac float64, r int) *fxSource {
	n := ww * wh
	s := &fxSource{
		w: ww, h: wh,
		r: make([]uint16, n), g: make([]uint16, n), b: make([]uint16, n),
		a: make([]uint16, n),
	}
	// 255*frac is the coc at which a pixel counts fully toward this level;
	// below it the weight ramps, which keeps the level boundaries from
	// printing as contours in a smooth depth gradient.
	full := math.Max(1, 255*frac)
	var wq [256]uint16
	for v := range wq {
		wq[v] = uint16(math.Round(65535 * math.Min(float64(v)/full, 1)))
	}
	fxBands(wh, func(y0, y1 int) {
		for j := y0 * ww; j < y1*ww; j++ {
			pw := int(wq[coc[j]])
			if pw == 0 {
				continue
			}
			s.r[j] = uint16(int(lin.r[j]) * pw / 65535)
			s.g[j] = uint16(int(lin.g[j]) * pw / 65535)
			s.b[j] = uint16(int(lin.b[j]) * pw / 65535)
			s.a[j] = uint16(pw)
		}
	})
	fxBlur(s, r)
	s.resolve()
	return s
}

// tiltComposite writes the graded defocus back over the render. Each output
// pixel's coc picks a position along the level ramp: 0 is the render's own
// pixel, tiltLevels is the widest blur, and the value between them is a lerp of
// the bracketing pair in linear light.
//
// This is a REPLACE, not a difference composite: the effect destroyed the
// region's detail, so the working buffer holds everything there is to know
// about it (fxComposite's argument). A pixel at coc 0 is skipped outright, so
// the in-focus band comes through byte-identical rather than through a
// linearize/re-encode round trip.
func tiltComposite(img *image.RGBA, coc []uint8, levels []tiltLevelView) {
	b := img.Bounds()
	w, h := b.Dx(), b.Dy()

	fxBands(h, func(y0, y1 int) {
		for y := y0; y < y1; y++ {
			row := img.Pix[y*img.Stride : y*img.Stride+w*4]
			crow := coc[y*w : (y+1)*w]
			for x := range w {
				c := crow[x]
				if c == 0 {
					continue // in focus: leave the render's own pixel alone
				}
				i := x * 4
				// The render's own pixel in linear light: the ramp's level 0,
				// and the fallback for a level that gathered no weight here.
				own := [3]float64{
					float64(fxLin[row[i]]), float64(fxLin[row[i+1]]), float64(fxLin[row[i+2]]),
				}
				// Position along the ramp, in level units; the bracketing pair
				// is k (the render itself at k == 0) and k+1.
				u := float64(c) / 255 * tiltLevels
				k := min(int(u), tiltLevels-1)
				t := u - float64(k)

				lo := own
				if k > 0 {
					lo = levels[k-1].sample(x, y, own)
				}
				hi := levels[k].sample(x, y, own)

				for ch := range 3 {
					v := lo[ch] + (hi[ch]-lo[ch])*t
					row[i+ch] = fxEnc[clampInt(int(v+0.5), 0, 65535)]
				}
			}
		}
	})
}

// tiltLevelView is one blur level plus the mapping from render pixels onto its
// own grid. Each level is sized to its own radius, so they no longer share one
// scale and the composite carries a view per level rather than a pair of
// factors for all of them.
type tiltLevelView struct {
	s      *fxSource
	sx, sy float64
	exact  bool
}

func newTiltLevelView(s *fxSource, w, h int) tiltLevelView {
	return tiltLevelView{
		s:     s,
		sx:    float64(s.w) / float64(w),
		sy:    float64(s.h) / float64(h),
		exact: s.w == w && s.h == h,
	}
}

// sample reads the level at an output pixel, falling back to the render's own
// linear value where the level accumulated no weight — a pixel deep inside a
// sharp region that no defocused neighbour reached. Blending toward a zero
// there would darken the transition to black.
func (v tiltLevelView) sample(x, y int, own [3]float64) [3]float64 {
	if v.exact {
		j := y*v.s.w + x
		if v.s.a[j] == 0 {
			return own
		}
		return [3]float64{float64(v.s.r[j]), float64(v.s.g[j]), float64(v.s.b[j])}
	}
	sr, sg, sb, sa := v.s.sample((float64(x)+0.5)*v.sx-0.5, (float64(y)+0.5)*v.sy-0.5)
	if sa == 0 {
		return own
	}
	return [3]float64{float64(sr), float64(sg), float64(sb)}
}

// mergeSuppression folds b into a, keeping the stronger suppression per pixel,
// and returns the result — either input may be nil (no stage suppressed
// anything). a is reused when it can be, so the common single-source case
// allocates nothing.
func mergeSuppression(a, b []uint8) []uint8 {
	switch {
	case b == nil:
		return a
	case a == nil:
		return b
	case len(a) != len(b):
		return a // defensive: different render targets, never expected
	}
	for i, v := range b {
		if v > a[i] {
			a[i] = v
		}
	}
	return a
}
